// Code generated by structgen. DO NOT EDIT.

package keybindings

import "iter"

// Keybindings represents the settings for the app's keybindings.
type Keybindings struct {
	SwitchPanes Keybinding

	SelectItem  Keybinding
	CloseItem   Keybinding
	FilterItems Keybinding

	Help    Keybinding
	Suspend Keybinding
	Quit    Keybinding

	NavigateUp     Keybinding
	NavigateDown   Keybinding
	NavigateLeft   Keybinding
	NavigateRight  Keybinding
	NavigateTop    Keybinding
	NavigateBottom Keybinding

	Adapter struct {
		TogglePower        Keybinding
		ToggleDiscoverable Keybinding
		TogglePairable     Keybinding
		ToggleScan         Keybinding
	}

	Device struct {
		ToggleConnection  Keybinding
		TogglePairedState Keybinding
		Trust             Keybinding

		NetworkOptions Keybinding
		AudioProfiles  Keybinding
		Block          Keybinding
	}

	Filebrowser struct {
		CdForward Keybinding
		CdBack    Keybinding

		SelectOne        Keybinding
		SelectAll        Keybinding
		InvertSelection  Keybinding
		ConfirmSelection Keybinding

		Refresh           Keybinding
		ToggleHiddenFiles Keybinding
	}

	ADTree struct {
		ToggleNodes Keybinding
	}

	Operations struct {
		Cancel Keybinding
	}

	Transfers struct {
		Suspend Keybinding
		Resume  Keybinding
		Cancel  Keybinding
	}

	Player struct {
		ToggleDisplay      Keybinding
		ToggleMediaPlaying Keybinding

		Next         Keybinding
		Previous     Keybinding
		SeekForward  Keybinding
		SeekBackward Keybinding
		Stop         Keybinding
	}
}

const (
	_ KeyID = iota
	KeyIDSwitchPanes
	KeyIDSelectItem
	KeyIDCloseItem
	KeyIDFilterItems
	KeyIDHelp
	KeyIDSuspend
	KeyIDQuit
	KeyIDNavigateUp
	KeyIDNavigateDown
	KeyIDNavigateLeft
	KeyIDNavigateRight
	KeyIDNavigateTop
	KeyIDNavigateBottom
	KeyIDAdapterTogglePower
	KeyIDAdapterToggleDiscoverable
	KeyIDAdapterTogglePairable
	KeyIDAdapterToggleScan
	KeyIDDeviceToggleConnection
	KeyIDDeviceTogglePairedState
	KeyIDDeviceTrust
	KeyIDDeviceNetworkOptions
	KeyIDDeviceAudioProfiles
	KeyIDDeviceBlock
	KeyIDFilebrowserCdForward
	KeyIDFilebrowserCdBack
	KeyIDFilebrowserSelectOne
	KeyIDFilebrowserSelectAll
	KeyIDFilebrowserInvertSelection
	KeyIDFilebrowserConfirmSelection
	KeyIDFilebrowserRefresh
	KeyIDFilebrowserToggleHiddenFiles
	KeyIDADTreeToggleNodes
	KeyIDOperationsCancel
	KeyIDTransfersSuspend
	KeyIDTransfersResume
	KeyIDTransfersCancel
	KeyIDPlayerToggleDisplay
	KeyIDPlayerToggleMediaPlaying
	KeyIDPlayerNext
	KeyIDPlayerPrevious
	KeyIDPlayerSeekForward
	KeyIDPlayerSeekBackward
	KeyIDPlayerStop
)

var _emptyCmpCfg = &Configuration{}

func defaultConfig() *Keybindings {
	k := &Keybindings{}

	k.SwitchPanes = NewKeybinding(
		KeyIDSwitchPanes, "tab",
		"SwitchPanes",
		"SwitchPanes",
	)
	k.SelectItem = NewKeybinding(
		KeyIDSelectItem, "enter",
		"SelectItem",
		"SelectItem",
	)
	k.CloseItem = NewKeybinding(
		KeyIDCloseItem, "esc",
		"CloseItem",
		"CloseItem",
	)
	k.FilterItems = NewKeybinding(
		KeyIDFilterItems, "/",
		"FilterItems",
		"FilterItems",
	)
	k.Help = NewKeybinding(
		KeyIDHelp, "?",
		"Help",
		"Help",
	)
	k.Suspend = NewKeybinding(
		KeyIDSuspend, "ctrl+z",
		"Suspend",
		"Suspend",
	)
	k.Quit = NewKeybinding(
		KeyIDQuit, "q",
		"Quit",
		"Quit",
	)
	k.NavigateUp = NewKeybinding(
		KeyIDNavigateUp, "up",
		"NavigateUp",
		"NavigateUp",
	)
	k.NavigateDown = NewKeybinding(
		KeyIDNavigateDown, "down",
		"NavigateDown",
		"NavigateDown",
	)
	k.NavigateLeft = NewKeybinding(
		KeyIDNavigateLeft, "left",
		"NavigateLeft",
		"NavigateLeft",
	)
	k.NavigateRight = NewKeybinding(
		KeyIDNavigateRight, "right",
		"NavigateRight",
		"NavigateRight",
	)
	k.NavigateTop = NewKeybinding(
		KeyIDNavigateTop, "pgup",
		"NavigateTop",
		"NavigateTop",
	)
	k.NavigateBottom = NewKeybinding(
		KeyIDNavigateBottom, "pgdown",
		"NavigateBottom",
		"NavigateBottom",
	)
	k.Adapter.TogglePower = NewKeybinding(
		KeyIDAdapterTogglePower, "o",
		"TogglePower",
		"TogglePower",
	)
	k.Adapter.ToggleDiscoverable = NewKeybinding(
		KeyIDAdapterToggleDiscoverable, "S",
		"ToggleDiscoverable",
		"ToggleDiscoverable",
	)
	k.Adapter.TogglePairable = NewKeybinding(
		KeyIDAdapterTogglePairable, "P",
		"TogglePairable",
		"TogglePairable",
	)
	k.Adapter.ToggleScan = NewKeybinding(
		KeyIDAdapterToggleScan, "s",
		"ToggleScan",
		"ToggleScan",
	)
	k.Device.ToggleConnection = NewKeybinding(
		KeyIDDeviceToggleConnection, "c",
		"ToggleConnection",
		"ToggleConnection",
	)
	k.Device.TogglePairedState = NewKeybinding(
		KeyIDDeviceTogglePairedState, "p",
		"TogglePairedState",
		"TogglePairedState",
	)
	k.Device.Trust = NewKeybinding(
		KeyIDDeviceTrust, "t",
		"Trust",
		"Trust",
	)
	k.Device.NetworkOptions = NewKeybinding(
		KeyIDDeviceNetworkOptions, "n",
		"NetworkOptions",
		"NetworkOptions",
	)
	k.Device.AudioProfiles = NewKeybinding(
		KeyIDDeviceAudioProfiles, "A",
		"AudioProfiles",
		"AudioProfiles",
	)
	k.Device.Block = NewKeybinding(
		KeyIDDeviceBlock, "b",
		"Block",
		"Block",
	)
	k.Filebrowser.CdForward = NewKeybinding(
		KeyIDFilebrowserCdForward, "right",
		"CdForward",
		"CdForward",
	)
	k.Filebrowser.CdBack = NewKeybinding(
		KeyIDFilebrowserCdBack, "left",
		"CdBack",
		"CdBack",
	)
	k.Filebrowser.SelectOne = NewKeybinding(
		KeyIDFilebrowserSelectOne, " ",
		"SelectOne",
		"SelectOne",
	)
	k.Filebrowser.SelectAll = NewKeybinding(
		KeyIDFilebrowserSelectAll, "A",
		"SelectAll",
		"SelectAll",
	)
	k.Filebrowser.InvertSelection = NewKeybinding(
		KeyIDFilebrowserInvertSelection, "a",
		"InvertSelection",
		"InvertSelection",
	)
	k.Filebrowser.ConfirmSelection = NewKeybinding(
		KeyIDFilebrowserConfirmSelection, "ctrl+s",
		"ConfirmSelection",
		"ConfirmSelection",
	)
	k.Filebrowser.Refresh = NewKeybinding(
		KeyIDFilebrowserRefresh, "ctrl+r",
		"Refresh",
		"Refresh",
	)
	k.Filebrowser.ToggleHiddenFiles = NewKeybinding(
		KeyIDFilebrowserToggleHiddenFiles, ".",
		"ToggleHiddenFiles",
		"ToggleHiddenFiles",
	)
	k.ADTree.ToggleNodes = NewKeybinding(
		KeyIDADTreeToggleNodes, "right",
		"ToggleNodes",
		"ToggleNodes",
	)
	k.Operations.Cancel = NewKeybinding(
		KeyIDOperationsCancel, "x",
		"Cancel",
		"Cancel",
	)
	k.Transfers.Suspend = NewKeybinding(
		KeyIDTransfersSuspend, "s",
		"Suspend",
		"Suspend",
	)
	k.Transfers.Resume = NewKeybinding(
		KeyIDTransfersResume, "r",
		"Resume",
		"Resume",
	)
	k.Transfers.Cancel = NewKeybinding(
		KeyIDTransfersCancel, "x",
		"Cancel",
		"Cancel",
	)
	k.Player.ToggleDisplay = NewKeybinding(
		KeyIDPlayerToggleDisplay, "M",
		"ToggleDisplay",
		"ToggleDisplay",
	)
	k.Player.ToggleMediaPlaying = NewKeybinding(
		KeyIDPlayerToggleMediaPlaying, " ",
		"ToggleMediaPlaying",
		"ToggleMediaPlaying",
	)
	k.Player.Next = NewKeybinding(
		KeyIDPlayerNext, ">",
		"Next",
		"Next",
	)
	k.Player.Previous = NewKeybinding(
		KeyIDPlayerPrevious, "<",
		"Previous",
		"Previous",
	)
	k.Player.SeekForward = NewKeybinding(
		KeyIDPlayerSeekForward, "right",
		"SeekForward",
		"SeekForward",
	)
	k.Player.SeekBackward = NewKeybinding(
		KeyIDPlayerSeekBackward, "left",
		"SeekBackward",
		"SeekBackward",
	)
	k.Player.Stop = NewKeybinding(
		KeyIDPlayerStop, "]",
		"Stop",
		"Stop",
	)
	return k
}

type parseKeybindingInfo struct {
	kb     *Keybinding
	cmpCfg string
}

func iterProperties(kb *Keybindings, cfg *Configuration) iter.Seq[parseKeybindingInfo] {
	if cfg == nil {
		cfg = _emptyCmpCfg
	}

	return func(yield func(parseKeybindingInfo) bool) {
		for i := range 43 {
			if !yield(getProperty(kb, cfg, i)) {
				return
			}
		}
	}
}

func getProperty(kb *Keybindings, cfg *Configuration, pos int) parseKeybindingInfo {
	p := parseKeybindingInfo{}

	switch pos {
	case 0:
		p.kb = &kb.SwitchPanes
		p.cmpCfg = cfg.SwitchPanes

	case 1:
		p.kb = &kb.SelectItem
		p.cmpCfg = cfg.SelectItem

	case 2:
		p.kb = &kb.CloseItem
		p.cmpCfg = cfg.CloseItem

	case 3:
		p.kb = &kb.FilterItems
		p.cmpCfg = cfg.FilterItems

	case 4:
		p.kb = &kb.Help
		p.cmpCfg = cfg.Help

	case 5:
		p.kb = &kb.Suspend
		p.cmpCfg = cfg.Suspend

	case 6:
		p.kb = &kb.Quit
		p.cmpCfg = cfg.Quit

	case 7:
		p.kb = &kb.NavigateUp
		p.cmpCfg = cfg.NavigateUp

	case 8:
		p.kb = &kb.NavigateDown
		p.cmpCfg = cfg.NavigateDown

	case 9:
		p.kb = &kb.NavigateLeft
		p.cmpCfg = cfg.NavigateLeft

	case 10:
		p.kb = &kb.NavigateRight
		p.cmpCfg = cfg.NavigateRight

	case 11:
		p.kb = &kb.NavigateTop
		p.cmpCfg = cfg.NavigateTop

	case 12:
		p.kb = &kb.NavigateBottom
		p.cmpCfg = cfg.NavigateBottom

	case 13:
		p.kb = &kb.Adapter.TogglePower
		p.cmpCfg = cfg.Adapter.TogglePower

	case 14:
		p.kb = &kb.Adapter.ToggleDiscoverable
		p.cmpCfg = cfg.Adapter.ToggleDiscoverable

	case 15:
		p.kb = &kb.Adapter.TogglePairable
		p.cmpCfg = cfg.Adapter.TogglePairable

	case 16:
		p.kb = &kb.Adapter.ToggleScan
		p.cmpCfg = cfg.Adapter.ToggleScan

	case 17:
		p.kb = &kb.Device.ToggleConnection
		p.cmpCfg = cfg.Device.ToggleConnection

	case 18:
		p.kb = &kb.Device.TogglePairedState
		p.cmpCfg = cfg.Device.TogglePairedState

	case 19:
		p.kb = &kb.Device.Trust
		p.cmpCfg = cfg.Device.Trust

	case 20:
		p.kb = &kb.Device.NetworkOptions
		p.cmpCfg = cfg.Device.NetworkOptions

	case 21:
		p.kb = &kb.Device.AudioProfiles
		p.cmpCfg = cfg.Device.AudioProfiles

	case 22:
		p.kb = &kb.Device.Block
		p.cmpCfg = cfg.Device.Block

	case 23:
		p.kb = &kb.Filebrowser.CdForward
		p.cmpCfg = cfg.Filebrowser.CdForward

	case 24:
		p.kb = &kb.Filebrowser.CdBack
		p.cmpCfg = cfg.Filebrowser.CdBack

	case 25:
		p.kb = &kb.Filebrowser.SelectOne
		p.cmpCfg = cfg.Filebrowser.SelectOne

	case 26:
		p.kb = &kb.Filebrowser.SelectAll
		p.cmpCfg = cfg.Filebrowser.SelectAll

	case 27:
		p.kb = &kb.Filebrowser.InvertSelection
		p.cmpCfg = cfg.Filebrowser.InvertSelection

	case 28:
		p.kb = &kb.Filebrowser.ConfirmSelection
		p.cmpCfg = cfg.Filebrowser.ConfirmSelection

	case 29:
		p.kb = &kb.Filebrowser.Refresh
		p.cmpCfg = cfg.Filebrowser.Refresh

	case 30:
		p.kb = &kb.Filebrowser.ToggleHiddenFiles
		p.cmpCfg = cfg.Filebrowser.ToggleHiddenFiles

	case 31:
		p.kb = &kb.ADTree.ToggleNodes
		p.cmpCfg = cfg.ADTree.ToggleNodes

	case 32:
		p.kb = &kb.Operations.Cancel
		p.cmpCfg = cfg.Operations.Cancel

	case 33:
		p.kb = &kb.Transfers.Suspend
		p.cmpCfg = cfg.Transfers.Suspend

	case 34:
		p.kb = &kb.Transfers.Resume
		p.cmpCfg = cfg.Transfers.Resume

	case 35:
		p.kb = &kb.Transfers.Cancel
		p.cmpCfg = cfg.Transfers.Cancel

	case 36:
		p.kb = &kb.Player.ToggleDisplay
		p.cmpCfg = cfg.Player.ToggleDisplay

	case 37:
		p.kb = &kb.Player.ToggleMediaPlaying
		p.cmpCfg = cfg.Player.ToggleMediaPlaying

	case 38:
		p.kb = &kb.Player.Next
		p.cmpCfg = cfg.Player.Next

	case 39:
		p.kb = &kb.Player.Previous
		p.cmpCfg = cfg.Player.Previous

	case 40:
		p.kb = &kb.Player.SeekForward
		p.cmpCfg = cfg.Player.SeekForward

	case 41:
		p.kb = &kb.Player.SeekBackward
		p.cmpCfg = cfg.Player.SeekBackward

	case 42:
		p.kb = &kb.Player.Stop
		p.cmpCfg = cfg.Player.Stop

	}

	return p
}
