// Code generated by structgen. DO NOT EDIT.

package keybindings

import "iter"

// Keybindings represents the settings for the app's keybindings.
type Keybindings struct {
	SwitchPanes Keybinding

	SelectItem  Keybinding
	CloseItem   Keybinding
	FilterItems Keybinding

	Help    Keybinding
	Suspend Keybinding
	Quit    Keybinding

	NavigateUp     Keybinding
	NavigateDown   Keybinding
	NavigateLeft   Keybinding
	NavigateRight  Keybinding
	NavigateTop    Keybinding
	NavigateBottom Keybinding

	Adapter struct {
		TogglePower        Keybinding
		ToggleDiscoverable Keybinding
		TogglePairable     Keybinding
		ToggleScan         Keybinding
	}

	Device struct {
		ToggleConnection  Keybinding
		TogglePairedState Keybinding
		Trust             Keybinding

		SendFiles      Keybinding
		NetworkOptions Keybinding
		AudioProfiles  Keybinding
		Block          Keybinding
	}

	Filebrowser struct {
		CdForward Keybinding
		CdBack    Keybinding

		SelectOne        Keybinding
		SelectAll        Keybinding
		InvertSelection  Keybinding
		ConfirmSelection Keybinding

		Refresh           Keybinding
		ToggleHiddenFiles Keybinding
	}

	ADTree struct {
		ToggleNodes Keybinding
	}

	Operations struct {
		Cancel Keybinding
	}

	Transfers struct {
		Suspend Keybinding
		Resume  Keybinding
		Cancel  Keybinding
	}

	Player struct {
		ToggleDisplay      Keybinding
		ToggleMediaPlaying Keybinding

		Next         Keybinding
		Previous     Keybinding
		SeekForward  Keybinding
		SeekBackward Keybinding
		Stop         Keybinding
	}
}

const (
	KeyNone KeyID = iota
	KeySwitchPanes
	KeySelectItem
	KeyCloseItem
	KeyFilterItems
	KeyHelp
	KeySuspend
	KeyQuit
	KeyNavigateUp
	KeyNavigateDown
	KeyNavigateLeft
	KeyNavigateRight
	KeyNavigateTop
	KeyNavigateBottom
	KeyAdapterTogglePower
	KeyAdapterToggleDiscoverable
	KeyAdapterTogglePairable
	KeyAdapterToggleScan
	KeyDeviceToggleConnection
	KeyDeviceTogglePairedState
	KeyDeviceTrust
	KeyDeviceSendFiles
	KeyDeviceNetworkOptions
	KeyDeviceAudioProfiles
	KeyDeviceBlock
	KeyFilebrowserCdForward
	KeyFilebrowserCdBack
	KeyFilebrowserSelectOne
	KeyFilebrowserSelectAll
	KeyFilebrowserInvertSelection
	KeyFilebrowserConfirmSelection
	KeyFilebrowserRefresh
	KeyFilebrowserToggleHiddenFiles
	KeyADTreeToggleNodes
	KeyOperationsCancel
	KeyTransfersSuspend
	KeyTransfersResume
	KeyTransfersCancel
	KeyPlayerToggleDisplay
	KeyPlayerToggleMediaPlaying
	KeyPlayerNext
	KeyPlayerPrevious
	KeyPlayerSeekForward
	KeyPlayerSeekBackward
	KeyPlayerStop
)

var _emptyCmpCfg = &Configuration{}

func defaultConfig() *Keybindings {
	k := &Keybindings{}

	k.SwitchPanes = NewKeybinding(
		KeySwitchPanes, "tab",
		"SwitchPanes",
		"SwitchPanes",
	)
	k.SelectItem = NewKeybinding(
		KeySelectItem, "enter",
		"SelectItem",
		"SelectItem",
	)
	k.CloseItem = NewKeybinding(
		KeyCloseItem, "esc",
		"CloseItem",
		"CloseItem",
	)
	k.FilterItems = NewKeybinding(
		KeyFilterItems, "/",
		"FilterItems",
		"FilterItems",
	)
	k.Help = NewKeybinding(
		KeyHelp, "?",
		"Help",
		"Help",
	)
	k.Suspend = NewKeybinding(
		KeySuspend, "ctrl+z",
		"Suspend",
		"Suspend",
	)
	k.Quit = NewKeybinding(
		KeyQuit, "q",
		"Quit",
		"Quit",
	)
	k.NavigateUp = NewKeybinding(
		KeyNavigateUp, "up",
		"NavigateUp",
		"NavigateUp",
	)
	k.NavigateDown = NewKeybinding(
		KeyNavigateDown, "down",
		"NavigateDown",
		"NavigateDown",
	)
	k.NavigateLeft = NewKeybinding(
		KeyNavigateLeft, "left",
		"NavigateLeft",
		"NavigateLeft",
	)
	k.NavigateRight = NewKeybinding(
		KeyNavigateRight, "right",
		"NavigateRight",
		"NavigateRight",
	)
	k.NavigateTop = NewKeybinding(
		KeyNavigateTop, "pgup",
		"NavigateTop",
		"NavigateTop",
	)
	k.NavigateBottom = NewKeybinding(
		KeyNavigateBottom, "pgdown",
		"NavigateBottom",
		"NavigateBottom",
	)
	k.Adapter.TogglePower = NewKeybinding(
		KeyAdapterTogglePower, "o",
		"TogglePower",
		"TogglePower",
	)
	k.Adapter.ToggleDiscoverable = NewKeybinding(
		KeyAdapterToggleDiscoverable, "S",
		"ToggleDiscoverable",
		"ToggleDiscoverable",
	)
	k.Adapter.TogglePairable = NewKeybinding(
		KeyAdapterTogglePairable, "P",
		"TogglePairable",
		"TogglePairable",
	)
	k.Adapter.ToggleScan = NewKeybinding(
		KeyAdapterToggleScan, "s",
		"ToggleScan",
		"ToggleScan",
	)
	k.Device.ToggleConnection = NewKeybinding(
		KeyDeviceToggleConnection, "c",
		"ToggleConnection",
		"ToggleConnection",
	)
	k.Device.TogglePairedState = NewKeybinding(
		KeyDeviceTogglePairedState, "p",
		"TogglePairedState",
		"TogglePairedState",
	)
	k.Device.Trust = NewKeybinding(
		KeyDeviceTrust, "t",
		"Trust",
		"Trust",
	)
	k.Device.SendFiles = NewKeybinding(
		KeyDeviceSendFiles, "f",
		"SendFiles",
		"SendFiles",
	)
	k.Device.NetworkOptions = NewKeybinding(
		KeyDeviceNetworkOptions, "n",
		"NetworkOptions",
		"NetworkOptions",
	)
	k.Device.AudioProfiles = NewKeybinding(
		KeyDeviceAudioProfiles, "A",
		"AudioProfiles",
		"AudioProfiles",
	)
	k.Device.Block = NewKeybinding(
		KeyDeviceBlock, "b",
		"Block",
		"Block",
	)
	k.Filebrowser.CdForward = NewKeybinding(
		KeyFilebrowserCdForward, "right",
		"CdForward",
		"CdForward",
	)
	k.Filebrowser.CdBack = NewKeybinding(
		KeyFilebrowserCdBack, "left",
		"CdBack",
		"CdBack",
	)
	k.Filebrowser.SelectOne = NewKeybinding(
		KeyFilebrowserSelectOne, "space",
		"SelectOne",
		"SelectOne",
	)
	k.Filebrowser.SelectAll = NewKeybinding(
		KeyFilebrowserSelectAll, "A",
		"SelectAll",
		"SelectAll",
	)
	k.Filebrowser.InvertSelection = NewKeybinding(
		KeyFilebrowserInvertSelection, "a",
		"InvertSelection",
		"InvertSelection",
	)
	k.Filebrowser.ConfirmSelection = NewKeybinding(
		KeyFilebrowserConfirmSelection, "ctrl+s",
		"ConfirmSelection",
		"ConfirmSelection",
	)
	k.Filebrowser.Refresh = NewKeybinding(
		KeyFilebrowserRefresh, "ctrl+r",
		"Refresh",
		"Refresh",
	)
	k.Filebrowser.ToggleHiddenFiles = NewKeybinding(
		KeyFilebrowserToggleHiddenFiles, ".",
		"ToggleHiddenFiles",
		"ToggleHiddenFiles",
	)
	k.ADTree.ToggleNodes = NewKeybinding(
		KeyADTreeToggleNodes, "right",
		"ToggleNodes",
		"ToggleNodes",
	)
	k.Operations.Cancel = NewKeybinding(
		KeyOperationsCancel, "x",
		"Cancel",
		"Cancel",
	)
	k.Transfers.Suspend = NewKeybinding(
		KeyTransfersSuspend, "s",
		"Suspend",
		"Suspend",
	)
	k.Transfers.Resume = NewKeybinding(
		KeyTransfersResume, "r",
		"Resume",
		"Resume",
	)
	k.Transfers.Cancel = NewKeybinding(
		KeyTransfersCancel, "x",
		"Cancel",
		"Cancel",
	)
	k.Player.ToggleDisplay = NewKeybinding(
		KeyPlayerToggleDisplay, "M",
		"ToggleDisplay",
		"ToggleDisplay",
	)
	k.Player.ToggleMediaPlaying = NewKeybinding(
		KeyPlayerToggleMediaPlaying, "space",
		"ToggleMediaPlaying",
		"ToggleMediaPlaying",
	)
	k.Player.Next = NewKeybinding(
		KeyPlayerNext, ">",
		"Next",
		"Next",
	)
	k.Player.Previous = NewKeybinding(
		KeyPlayerPrevious, "<",
		"Previous",
		"Previous",
	)
	k.Player.SeekForward = NewKeybinding(
		KeyPlayerSeekForward, "right",
		"SeekForward",
		"SeekForward",
	)
	k.Player.SeekBackward = NewKeybinding(
		KeyPlayerSeekBackward, "left",
		"SeekBackward",
		"SeekBackward",
	)
	k.Player.Stop = NewKeybinding(
		KeyPlayerStop, "]",
		"Stop",
		"Stop",
	)
	return k
}

type parseKeybindingInfo struct {
	kb     *Keybinding
	cmpCfg string
}

func iterProperties(kb *Keybindings, cfg *Configuration) iter.Seq[parseKeybindingInfo] {
	if cfg == nil {
		cfg = _emptyCmpCfg
	}

	return func(yield func(parseKeybindingInfo) bool) {
		for i := range 44 {
			if !yield(getProperty(kb, cfg, i)) {
				return
			}
		}
	}
}

func getProperty(kb *Keybindings, cfg *Configuration, pos int) parseKeybindingInfo {
	p := parseKeybindingInfo{}

	switch pos {
	case 0:
		p.kb = &kb.SwitchPanes
		p.cmpCfg = cfg.SwitchPanes

	case 1:
		p.kb = &kb.SelectItem
		p.cmpCfg = cfg.SelectItem

	case 2:
		p.kb = &kb.CloseItem
		p.cmpCfg = cfg.CloseItem

	case 3:
		p.kb = &kb.FilterItems
		p.cmpCfg = cfg.FilterItems

	case 4:
		p.kb = &kb.Help
		p.cmpCfg = cfg.Help

	case 5:
		p.kb = &kb.Suspend
		p.cmpCfg = cfg.Suspend

	case 6:
		p.kb = &kb.Quit
		p.cmpCfg = cfg.Quit

	case 7:
		p.kb = &kb.NavigateUp
		p.cmpCfg = cfg.NavigateUp

	case 8:
		p.kb = &kb.NavigateDown
		p.cmpCfg = cfg.NavigateDown

	case 9:
		p.kb = &kb.NavigateLeft
		p.cmpCfg = cfg.NavigateLeft

	case 10:
		p.kb = &kb.NavigateRight
		p.cmpCfg = cfg.NavigateRight

	case 11:
		p.kb = &kb.NavigateTop
		p.cmpCfg = cfg.NavigateTop

	case 12:
		p.kb = &kb.NavigateBottom
		p.cmpCfg = cfg.NavigateBottom

	case 13:
		p.kb = &kb.Adapter.TogglePower
		p.cmpCfg = cfg.Adapter.TogglePower

	case 14:
		p.kb = &kb.Adapter.ToggleDiscoverable
		p.cmpCfg = cfg.Adapter.ToggleDiscoverable

	case 15:
		p.kb = &kb.Adapter.TogglePairable
		p.cmpCfg = cfg.Adapter.TogglePairable

	case 16:
		p.kb = &kb.Adapter.ToggleScan
		p.cmpCfg = cfg.Adapter.ToggleScan

	case 17:
		p.kb = &kb.Device.ToggleConnection
		p.cmpCfg = cfg.Device.ToggleConnection

	case 18:
		p.kb = &kb.Device.TogglePairedState
		p.cmpCfg = cfg.Device.TogglePairedState

	case 19:
		p.kb = &kb.Device.Trust
		p.cmpCfg = cfg.Device.Trust

	case 20:
		p.kb = &kb.Device.SendFiles
		p.cmpCfg = cfg.Device.SendFiles

	case 21:
		p.kb = &kb.Device.NetworkOptions
		p.cmpCfg = cfg.Device.NetworkOptions

	case 22:
		p.kb = &kb.Device.AudioProfiles
		p.cmpCfg = cfg.Device.AudioProfiles

	case 23:
		p.kb = &kb.Device.Block
		p.cmpCfg = cfg.Device.Block

	case 24:
		p.kb = &kb.Filebrowser.CdForward
		p.cmpCfg = cfg.Filebrowser.CdForward

	case 25:
		p.kb = &kb.Filebrowser.CdBack
		p.cmpCfg = cfg.Filebrowser.CdBack

	case 26:
		p.kb = &kb.Filebrowser.SelectOne
		p.cmpCfg = cfg.Filebrowser.SelectOne

	case 27:
		p.kb = &kb.Filebrowser.SelectAll
		p.cmpCfg = cfg.Filebrowser.SelectAll

	case 28:
		p.kb = &kb.Filebrowser.InvertSelection
		p.cmpCfg = cfg.Filebrowser.InvertSelection

	case 29:
		p.kb = &kb.Filebrowser.ConfirmSelection
		p.cmpCfg = cfg.Filebrowser.ConfirmSelection

	case 30:
		p.kb = &kb.Filebrowser.Refresh
		p.cmpCfg = cfg.Filebrowser.Refresh

	case 31:
		p.kb = &kb.Filebrowser.ToggleHiddenFiles
		p.cmpCfg = cfg.Filebrowser.ToggleHiddenFiles

	case 32:
		p.kb = &kb.ADTree.ToggleNodes
		p.cmpCfg = cfg.ADTree.ToggleNodes

	case 33:
		p.kb = &kb.Operations.Cancel
		p.cmpCfg = cfg.Operations.Cancel

	case 34:
		p.kb = &kb.Transfers.Suspend
		p.cmpCfg = cfg.Transfers.Suspend

	case 35:
		p.kb = &kb.Transfers.Resume
		p.cmpCfg = cfg.Transfers.Resume

	case 36:
		p.kb = &kb.Transfers.Cancel
		p.cmpCfg = cfg.Transfers.Cancel

	case 37:
		p.kb = &kb.Player.ToggleDisplay
		p.cmpCfg = cfg.Player.ToggleDisplay

	case 38:
		p.kb = &kb.Player.ToggleMediaPlaying
		p.cmpCfg = cfg.Player.ToggleMediaPlaying

	case 39:
		p.kb = &kb.Player.Next
		p.cmpCfg = cfg.Player.Next

	case 40:
		p.kb = &kb.Player.Previous
		p.cmpCfg = cfg.Player.Previous

	case 41:
		p.kb = &kb.Player.SeekForward
		p.cmpCfg = cfg.Player.SeekForward

	case 42:
		p.kb = &kb.Player.SeekBackward
		p.cmpCfg = cfg.Player.SeekBackward

	case 43:
		p.kb = &kb.Player.Stop
		p.cmpCfg = cfg.Player.Stop

	}

	return p
}
