package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"github.com/dave/dst/dstutil"
	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

const (
	pkgName  = "theme"
	themeDir = "ui/theme"
)

const (
	configFileName   = "config.go"
	configStructName = "Configuration"
)

const (
	themeGenFileName   = "theme.gen.go"
	themeStructName    = "Theme"
	themeStructComment = "// Theme represents the settings for the app's theme."
)

func main() {
	dir, err := os.Getwd()
	if err != nil {
		exit(err)
	}

	configFilePath := filepath.Join(dir, configFileName)
	themeGenFilePath := filepath.Join(dir, themeGenFileName)

	fset := token.NewFileSet()

	cfgDst, err := decorator.ParseFile(fset, configFilePath, nil, parser.AllErrors)
	if err != nil {
		exit(err)
	}

	dstutil.Apply(cfgDst, func(c *dstutil.Cursor) bool {
		n := c.Node()
		if n == nil {
			return true
		}

		ts, st, exists, skip := matchStructType(n, configStructName)
		switch {
		case !skip && !exists:
			deleteNodeFromCursor(c)
			return true

		case exists:
			modifyStruct(
				&modStructArg{
					fset:       fset,
					cfgFile:    cfgDst,
					parentNode: c.Parent(),
					ts:         ts,
					st:         st,
					origName:   configStructName,
					newName:    themeStructName,
					comment:    themeStructComment,
				},
			)
			return true
		}

		switch v := n.(type) {
		case *dst.FuncDecl:
			if !matchFuncRecvType(v, themeStructName) {
				deleteNodeFromCursor(c)
			}

		default:
		}

		return true
	}, nil)

	err = writeCodeToFile(cfgDst, themeGenFileName, themeGenFilePath)
	if err != nil {
		exit(err)
	}
}

func writeCodeToFile(generatedDst *dst.File, fileName, filePath string) error {
	impDir, closeFunc, err := prepareAllImports(pkgName)
	if err != nil {
		return err
	}
	defer closeFunc()

	var b bytes.Buffer
	defer b.Reset()

	decorator.Fprint(&b, generatedDst)

	proc, err := imports.Process(filepath.Join(impDir, fileName), b.Bytes(), nil)
	if err != nil {
		return err
	}

	file, err := openFileToWrite(filePath)
	if err != nil {
		return err
	}

	_, err = file.WriteString("// Generated by themegen. DO NOT EDIT.\n\n")
	if err != nil {
		return err
	}

	_, err = file.Write(proc)
	if err != nil {
		return err
	}

	return file.Close()
}

func matchStructType(n dst.Node, name string) (ts *dst.TypeSpec, st *dst.StructType, exists bool, skip bool) {
	typeSpec, ok := n.(*dst.TypeSpec)
	if !ok {
		return nil, nil, false, true
	}

	st, ok = typeSpec.Type.(*dst.StructType)
	if !ok {
		return nil, nil, false, true
	}

	return typeSpec, st, typeSpec.Name.Name == name, false
}

func matchFuncRecvType(fnType *dst.FuncDecl, recvTypeName string) (exists bool) {
	recv := fnType.Recv
	if recv == nil || len(recv.List) == 0 {
		return false
	}

	for _, rt := range recv.List {
		expr := rt.Type
		if expr == nil {
			continue
		}

		switch v := expr.(type) {
		case *dst.Ident:
			if v.Name == recvTypeName {
				return true
			}

		case *dst.StarExpr:
			if ident, ok := v.X.(*dst.Ident); ok && ident.Name == recvTypeName {
				return true
			}
		}
	}

	return false
}

func openFileToWrite(filePath string) (*os.File, error) {
	file, err := os.OpenFile(filePath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, os.ModePerm)
	return file, err
}

type modStructArg struct {
	fset *token.FileSet

	cfgFile    *dst.File
	parentNode dst.Node

	ts *dst.TypeSpec
	st *dst.StructType

	origName, newName, comment string
}

func modifyStruct(v *modStructArg) {
	v.ts.Name.Name = v.newName

	decs := v.parentNode.Decorations()
	decs.Before = dst.EmptyLine
	decs.After = dst.EmptyLine
	decs.Start.Clear()
	decs.Start.Append(v.comment)

	var sb strings.Builder

	fmt.Fprintf(&sb, "package %s\n\n", pkgName)

	fmt.Fprintf(&sb, "// IterProperties returns the iterator over matching properties of [%s] and [%s].\n", v.origName, v.newName)
	fmt.Fprintf(&sb, "func (t *%s) IterProperties(cfg *%s) iter.Seq2[string, *lipgloss.Style] {\n", v.newName, v.origName)
	fmt.Fprintf(&sb, "return func(yield func(cfgStr string, themeStyle *lipgloss.Style) bool) {\n")

	genStructAndAccessors(v.st, "", func(s string) {
		fmt.Fprintf(&sb, `if !yield(cfg.%s, &t.%s) {`, s, s)
		sb.WriteString("return")
		sb.WriteString("}\n\n")
	})

	sb.WriteString("}\n")
	sb.WriteString("}\n")

	f, err := decorator.ParseFile(v.fset, "part.go", sb.String(), parser.AllErrors)
	if err != nil {
		exit(err)
	}

	for _, decl := range f.Decls {
		if fn, ok := decl.(*dst.FuncDecl); ok {
			v.cfgFile.Decls = append(v.cfgFile.Decls, fn)
		}
	}
}

func genStructAndAccessors(st *dst.StructType, prefix string, accFunc func(string)) {
	for _, field := range st.Fields.List {
		for _, name := range field.Names {
			name := name.Name
			if prefix != "" {
				name = prefix + "." + name
			}

			switch ft := field.Type.(type) {
			case *dst.StructType:
				genStructAndAccessors(ft, name, accFunc)
				continue

			case *dst.Ident:
				if ft.Name != "string" {
					continue
				}

				field.Type = &dst.SelectorExpr{
					X:   &dst.Ident{Name: "lipgloss"},
					Sel: &dst.Ident{Name: "Style"},
				}
			}

			accFunc(name)
		}
	}
}

func deleteNodeFromCursor(c *dstutil.Cursor) {
	if c.Index() >= 0 {
		c.Delete()
	}
}

func prepareAllImports(pkgName string) (impDir string, closeFunc func(), err error) {
	impDir, err = os.MkdirTemp("", "bluetuith-themegen-*")
	if err != nil {
		return "", nil, err
	}

	projPath, err := projDirPath()
	if err != nil {
		return "", nil, err
	}

	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedImports | packages.NeedFiles,
		Dir:  projPath,
	}, "./...")
	if err != nil {
		return "", nil, err
	}

	var sb strings.Builder

	fmt.Fprintf(&sb, "package %s\n\nimport (\n", pkgName)

	importMap := make(map[string]string)
	for _, pkg := range pkgs {
		for _, imp := range pkg.Imports {
			importMap[imp.PkgPath] = imp.Name
		}
	}

	for importPath := range importMap {
		fmt.Fprintf(&sb, `"%s"`, importPath)
		sb.WriteString("\n")
	}

	sb.WriteString(")")

	fp := path.Join(impDir, "imports.go")
	file, err := openFileToWrite(fp)
	if err != nil {
		return "", nil, err
	}

	file.WriteString(sb.String())

	if err := file.Close(); err != nil {
		return "", nil, err
	}

	return impDir, func() {
		if err := os.Remove(fp); err != nil {
			panic(err)
		}

		if err := os.Remove(impDir); err != nil {
			panic(err)
		}
	}, nil
}

func projDirPath() (string, error) {
	cmd := exec.Command("go", "env", "GOMOD")

	out, err := cmd.Output()
	if err != nil {
		return "", err
	}

	str := string(out)
	str = strings.TrimSpace(str)

	if str == "" {
		return "", errors.New("GOMOD not found")
	}

	return filepath.Dir(filepath.Clean(str)), nil
}

//revive:disable
func exit(msg any) {
	fmt.Println(msg)

	os.Exit(1)
}
