package main

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"github.com/dave/dst/dstutil"
)

const (
	pkgName  = "theme"
	themeDir = "ui/theme"
)

const (
	configFile       = "config.go"
	configStructName = "Configuration"
)

const (
	themeGenFile       = "theme.gen.go"
	themeStructName    = "Theme"
	themeStructComment = "// Theme represents the settings for the app's theme."
)

func main() {
	dir, err := os.Getwd()
	if err != nil {
		exit(err)
	}

	configPath := filepath.Join(dir, configFile)
	themeGenPath := filepath.Join(dir, themeGenFile)

	fset := token.NewFileSet()

	cfgFile, err := decorator.ParseFile(fset, configPath, nil, parser.AllErrors)
	if err != nil {
		exit(err)
	}

	dstutil.Apply(cfgFile, func(c *dstutil.Cursor) bool {
		n := c.Node()
		if n == nil {
			return true
		}

		ts, st, exists, skip := matchStructType(n, configStructName)
		switch {
		case !skip && !exists:
			deleteNodeFromCursor(c)
			return true

		case exists:
			modifyStruct(
				&modStructArg{
					fset:       fset,
					cfgFile:    cfgFile,
					parentNode: c.Parent(),
					ts:         ts,
					st:         st,
					origName:   configStructName,
					newName:    themeStructName,
					comment:    themeStructComment,
				},
			)
			return true
		}

		switch v := n.(type) {
		case *dst.FuncDecl:
			if !matchFuncRecvType(v, themeStructName) {
				deleteNodeFromCursor(c)
			}

		default:
		}

		return true
	}, nil)

	file, err := os.OpenFile(themeGenPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, os.ModePerm)
	if err != nil {
		exit(err)
	}

	file.WriteString("// Generated by themegen. DO NOT EDIT.\n\n")

	err = decorator.Fprint(file, cfgFile)
	if err != nil {
		exit(err)
	}

	err = file.Close()
	if err != nil {
		exit(err)
	}

	cmd := exec.Command("gopls", "imports", "-d", "-w", themeGenPath)

	output, err := cmd.Output()
	if err != nil {
		fmt.Println(themeGenPath)
		exit(err)
	}

	fmt.Println(string(output))
}

func deleteNodeFromCursor(c *dstutil.Cursor) {
	if c.Index() >= 0 {
		c.Delete()
	}
}

func matchStructType(n dst.Node, name string) (ts *dst.TypeSpec, st *dst.StructType, exists bool, skip bool) {
	typeSpec, ok := n.(*dst.TypeSpec)
	if !ok {
		return nil, nil, false, true
	}

	st, ok = typeSpec.Type.(*dst.StructType)
	if !ok {
		return nil, nil, false, true
	}

	return typeSpec, st, typeSpec.Name.Name == name, false
}

func matchFuncRecvType(fnType *dst.FuncDecl, recvTypeName string) (exists bool) {
	recv := fnType.Recv
	if recv == nil || len(recv.List) == 0 {
		return false
	}

	for _, rt := range recv.List {
		expr := rt.Type
		if expr == nil {
			continue
		}

		switch v := expr.(type) {
		case *dst.Ident:
			if v.Name == recvTypeName {
				return true
			}

		case *dst.StarExpr:
			if ident, ok := v.X.(*dst.Ident); ok && ident.Name == recvTypeName {
				return true
			}
		}
	}

	return false
}

type modStructArg struct {
	fset *token.FileSet

	cfgFile    *dst.File
	parentNode dst.Node

	ts *dst.TypeSpec
	st *dst.StructType

	origName, newName, comment string
}

func modifyStruct(v *modStructArg) {
	v.ts.Name.Name = v.newName

	decs := v.parentNode.Decorations()
	decs.Before = dst.EmptyLine
	decs.After = dst.EmptyLine
	decs.Start.Clear()
	decs.Start.Append(v.comment)

	var sb strings.Builder

	fmt.Fprintf(&sb, "package %s\n\n", pkgName)

	fmt.Fprintf(&sb, "// IterProperties returns the iterator over matching properties of [%s] and [%s].\n", v.origName, v.newName)
	fmt.Fprintf(&sb, "func (t *%s) IterProperties(cfg *%s) iter.Seq2[string, *lipgloss.Style] {\n", v.newName, v.origName)
	fmt.Fprintf(&sb, "return func(yield func(cfgStr string, themeStyle *lipgloss.Style) bool) {\n")

	genStructAndAccessors(v.st, "", func(s string) {
		fmt.Fprintf(&sb, `if !yield(cfg.%s, &t.%s) {`, s, s)
		sb.WriteString("return")
		sb.WriteString("}\n\n")
	})

	sb.WriteString("}\n")
	sb.WriteString("}\n")

	f, err := decorator.ParseFile(v.fset, "part.go", sb.String(), parser.AllErrors)
	if err != nil {
		exit(err)
	}

	for _, decl := range f.Decls {
		if fn, ok := decl.(*dst.FuncDecl); ok {
			v.cfgFile.Decls = append(v.cfgFile.Decls, fn)
		}
	}
}

func genStructAndAccessors(st *dst.StructType, prefix string, accFunc func(string)) {
	for _, field := range st.Fields.List {
		for _, name := range field.Names {
			name := name.Name
			if prefix != "" {
				name = prefix + "." + name
			}

			switch ft := field.Type.(type) {
			case *dst.StructType:
				genStructAndAccessors(ft, name, accFunc)
				continue

			case *dst.Ident:
				if ft.Name != "string" {
					continue
				}

				field.Type = &dst.SelectorExpr{
					X:   &dst.Ident{Name: "lipgloss"},
					Sel: &dst.Ident{Name: "Style"},
				}
			}

			accFunc(name)
		}
	}
}

//revive:disable
func exit(msg any) {
	fmt.Println(msg)

	os.Exit(1)
}
