// Code generated by structgen. DO NOT EDIT.

package keybindings

import (
	"iter"

	"github.com/gdamore/tcell/v3"
)

// Keybindings represents the settings for the app's keybindings.
type Keybindings struct {
	SelectItem  Keybinding
	CloseItem   Keybinding
	FilterItems Keybinding

	Help    Keybinding
	Suspend Keybinding
	Quit    Keybinding

	NavigateUp     Keybinding
	NavigateDown   Keybinding
	NavigateLeft   Keybinding
	NavigateRight  Keybinding
	NavigateTop    Keybinding
	NavigateBottom Keybinding

	Adapter struct {
		TogglePower        Keybinding
		ToggleDiscoverable Keybinding
		TogglePairable     Keybinding
		ToggleScan         Keybinding
	}

	Device struct {
		ToggleConnection  Keybinding
		TogglePairedState Keybinding
		Trust             Keybinding

		SendFiles      Keybinding
		NetworkOptions Keybinding
		AudioProfiles  Keybinding
		Block          Keybinding
	}

	Filebrowser struct {
		CdForward Keybinding
		CdBack    Keybinding

		SelectOne        Keybinding
		SelectAll        Keybinding
		InvertSelection  Keybinding
		ConfirmSelection Keybinding

		Refresh           Keybinding
		ToggleHiddenFiles Keybinding
	}

	ADTree struct {
		ExpandOrSelect Keybinding
		TabPane        Keybinding
	}

	TabPane struct {
		Next     Keybinding
		Previous Keybinding
		ADTree   Keybinding
	}

	Information struct {
		Show Keybinding
	}

	Operations struct {
		Show     Keybinding
		Cancel   Keybinding
		ClearAll Keybinding
	}

	Transfers struct {
		Show    Keybinding
		Suspend Keybinding
		Resume  Keybinding
		Cancel  Keybinding
	}

	Log struct {
		Show Keybinding
	}

	Player struct {
		ToggleDisplay      Keybinding
		ToggleMediaPlaying Keybinding

		Next         Keybinding
		Previous     Keybinding
		SeekForward  Keybinding
		SeekBackward Keybinding
		Stop         Keybinding
	}
}

const (
	KeyNone KeyID = iota
	KeySelectItem
	KeyCloseItem
	KeyFilterItems
	KeyHelp
	KeySuspend
	KeyQuit
	KeyNavigateUp
	KeyNavigateDown
	KeyNavigateLeft
	KeyNavigateRight
	KeyNavigateTop
	KeyNavigateBottom
	KeyAdapterTogglePower
	KeyAdapterToggleDiscoverable
	KeyAdapterTogglePairable
	KeyAdapterToggleScan
	KeyDeviceToggleConnection
	KeyDeviceTogglePairedState
	KeyDeviceTrust
	KeyDeviceSendFiles
	KeyDeviceNetworkOptions
	KeyDeviceAudioProfiles
	KeyDeviceBlock
	KeyFilebrowserCdForward
	KeyFilebrowserCdBack
	KeyFilebrowserSelectOne
	KeyFilebrowserSelectAll
	KeyFilebrowserInvertSelection
	KeyFilebrowserConfirmSelection
	KeyFilebrowserRefresh
	KeyFilebrowserToggleHiddenFiles
	KeyADTreeExpandOrSelect
	KeyADTreeTabPane
	KeyTabPaneNext
	KeyTabPanePrevious
	KeyTabPaneADTree
	KeyInformationShow
	KeyOperationsShow
	KeyOperationsCancel
	KeyOperationsClearAll
	KeyTransfersShow
	KeyTransfersSuspend
	KeyTransfersResume
	KeyTransfersCancel
	KeyLogShow
	KeyPlayerToggleDisplay
	KeyPlayerToggleMediaPlaying
	KeyPlayerNext
	KeyPlayerPrevious
	KeyPlayerSeekForward
	KeyPlayerSeekBackward
	KeyPlayerStop
)

var _emptyCmpCfg = &Configuration{}

func defaultConfig() *Keybindings {
	k := &Keybindings{}

	k.SelectItem = newKeybinding(
		KeySelectItem, newTcellKey(tcell.Key(13), "", tcell.ModNone), "enter",
		"SelectItem",
		"SelectItem",
	)
	k.CloseItem = newKeybinding(
		KeyCloseItem, newTcellKey(tcell.Key(27), "", tcell.ModNone), "esc",
		"CloseItem",
		"CloseItem",
	)
	k.FilterItems = newKeybinding(
		KeyFilterItems, newTcellKey(tcell.Key(256), "/", tcell.ModNone), "/",
		"FilterItems",
		"FilterItems",
	)
	k.Help = newKeybinding(
		KeyHelp, newTcellKey(tcell.Key(256), "?", tcell.ModNone), "?",
		"Help",
		"Help",
	)
	k.Suspend = newKeybinding(
		KeySuspend, newTcellKey(tcell.Key(90), "", tcell.ModCtrl), "ctrl+z",
		"Suspend",
		"Suspend",
	)
	k.Quit = newKeybinding(
		KeyQuit, newTcellKey(tcell.Key(256), "q", tcell.ModNone), "q",
		"Quit",
		"Quit",
	)
	k.NavigateUp = newKeybinding(
		KeyNavigateUp, newTcellKey(tcell.Key(257), "", tcell.ModNone), "up",
		"NavigateUp",
		"NavigateUp",
	)
	k.NavigateDown = newKeybinding(
		KeyNavigateDown, newTcellKey(tcell.Key(258), "", tcell.ModNone), "down",
		"NavigateDown",
		"NavigateDown",
	)
	k.NavigateLeft = newKeybinding(
		KeyNavigateLeft, newTcellKey(tcell.Key(260), "", tcell.ModNone), "left",
		"NavigateLeft",
		"NavigateLeft",
	)
	k.NavigateRight = newKeybinding(
		KeyNavigateRight, newTcellKey(tcell.Key(259), "", tcell.ModNone), "right",
		"NavigateRight",
		"NavigateRight",
	)
	k.NavigateTop = newKeybinding(
		KeyNavigateTop, newTcellKey(tcell.Key(266), "", tcell.ModNone), "pgup",
		"NavigateTop",
		"NavigateTop",
	)
	k.NavigateBottom = newKeybinding(
		KeyNavigateBottom, newTcellKey(tcell.Key(267), "", tcell.ModNone), "pgdn",
		"NavigateBottom",
		"NavigateBottom",
	)
	k.Adapter.TogglePower = newKeybinding(
		KeyAdapterTogglePower, newTcellKey(tcell.Key(256), "o", tcell.ModNone), "o",
		"TogglePower",
		"TogglePower",
	)
	k.Adapter.ToggleDiscoverable = newKeybinding(
		KeyAdapterToggleDiscoverable, newTcellKey(tcell.Key(256), "S", tcell.ModNone), "S",
		"ToggleDiscoverable",
		"ToggleDiscoverable",
	)
	k.Adapter.TogglePairable = newKeybinding(
		KeyAdapterTogglePairable, newTcellKey(tcell.Key(256), "P", tcell.ModNone), "P",
		"TogglePairable",
		"TogglePairable",
	)
	k.Adapter.ToggleScan = newKeybinding(
		KeyAdapterToggleScan, newTcellKey(tcell.Key(256), "s", tcell.ModNone), "s",
		"ToggleScan",
		"ToggleScan",
	)
	k.Device.ToggleConnection = newKeybinding(
		KeyDeviceToggleConnection, newTcellKey(tcell.Key(256), "c", tcell.ModNone), "c",
		"ToggleConnection",
		"ToggleConnection",
	)
	k.Device.TogglePairedState = newKeybinding(
		KeyDeviceTogglePairedState, newTcellKey(tcell.Key(256), "p", tcell.ModNone), "p",
		"TogglePairedState",
		"TogglePairedState",
	)
	k.Device.Trust = newKeybinding(
		KeyDeviceTrust, newTcellKey(tcell.Key(256), "t", tcell.ModNone), "t",
		"Trust",
		"Trust",
	)
	k.Device.SendFiles = newKeybinding(
		KeyDeviceSendFiles, newTcellKey(tcell.Key(256), "f", tcell.ModNone), "f",
		"SendFiles",
		"SendFiles",
	)
	k.Device.NetworkOptions = newKeybinding(
		KeyDeviceNetworkOptions, newTcellKey(tcell.Key(256), "n", tcell.ModNone), "n",
		"NetworkOptions",
		"NetworkOptions",
	)
	k.Device.AudioProfiles = newKeybinding(
		KeyDeviceAudioProfiles, newTcellKey(tcell.Key(256), "A", tcell.ModNone), "A",
		"AudioProfiles",
		"AudioProfiles",
	)
	k.Device.Block = newKeybinding(
		KeyDeviceBlock, newTcellKey(tcell.Key(256), "b", tcell.ModNone), "b",
		"Block",
		"Block",
	)
	k.Filebrowser.CdForward = newKeybinding(
		KeyFilebrowserCdForward, newTcellKey(tcell.Key(259), "", tcell.ModNone), "right",
		"CdForward",
		"CdForward",
	)
	k.Filebrowser.CdBack = newKeybinding(
		KeyFilebrowserCdBack, newTcellKey(tcell.Key(260), "", tcell.ModNone), "left",
		"CdBack",
		"CdBack",
	)
	k.Filebrowser.SelectOne = newKeybinding(
		KeyFilebrowserSelectOne, newTcellKey(tcell.Key(256), " ", tcell.ModNone), " ",
		"SelectOne",
		"SelectOne",
	)
	k.Filebrowser.SelectAll = newKeybinding(
		KeyFilebrowserSelectAll, newTcellKey(tcell.Key(256), "A", tcell.ModNone), "A",
		"SelectAll",
		"SelectAll",
	)
	k.Filebrowser.InvertSelection = newKeybinding(
		KeyFilebrowserInvertSelection, newTcellKey(tcell.Key(256), "a", tcell.ModNone), "a",
		"InvertSelection",
		"InvertSelection",
	)
	k.Filebrowser.ConfirmSelection = newKeybinding(
		KeyFilebrowserConfirmSelection, newTcellKey(tcell.Key(83), "", tcell.ModCtrl), "ctrl+s",
		"ConfirmSelection",
		"ConfirmSelection",
	)
	k.Filebrowser.Refresh = newKeybinding(
		KeyFilebrowserRefresh, newTcellKey(tcell.Key(82), "", tcell.ModCtrl), "ctrl+r",
		"Refresh",
		"Refresh",
	)
	k.Filebrowser.ToggleHiddenFiles = newKeybinding(
		KeyFilebrowserToggleHiddenFiles, newTcellKey(tcell.Key(256), ".", tcell.ModNone), ".",
		"ToggleHiddenFiles",
		"ToggleHiddenFiles",
	)
	k.ADTree.ExpandOrSelect = newKeybinding(
		KeyADTreeExpandOrSelect, newTcellKey(tcell.Key(259), "", tcell.ModNone), "right",
		"ExpandOrSelect",
		"ExpandOrSelect",
	)
	k.ADTree.TabPane = newKeybinding(
		KeyADTreeTabPane, newTcellKey(tcell.Key(9), "", tcell.ModNone), "tab",
		"SwitchPanes",
		"SwitchPanes",
	)
	k.TabPane.Next = newKeybinding(
		KeyTabPaneNext, newTcellKey(tcell.Key(9), "", tcell.ModNone), "tab",
		"SwitchSections",
		"SwitchSections",
	)
	k.TabPane.Previous = newKeybinding(
		KeyTabPanePrevious, newTcellKey(tcell.Key(278), "", tcell.ModNone), "shift+tab",
		"SwitchSections",
		"SwitchSections",
	)
	k.TabPane.ADTree = newKeybinding(
		KeyTabPaneADTree, newTcellKey(tcell.Key(27), "", tcell.ModNone), "esc",
		"SwitchSections",
		"SwitchSections",
	)
	k.Information.Show = newKeybinding(
		KeyInformationShow, newTcellKey(tcell.Key(256), "I", tcell.ModNone), "I",
		"Information",
		"Information",
	)
	k.Operations.Show = newKeybinding(
		KeyOperationsShow, newTcellKey(tcell.Key(256), "O", tcell.ModNone), "O",
		"Operations",
		"Operations",
	)
	k.Operations.Cancel = newKeybinding(
		KeyOperationsCancel, newTcellKey(tcell.Key(256), "x", tcell.ModNone), "x",
		"Cancel",
		"Cancel",
	)
	k.Operations.ClearAll = newKeybinding(
		KeyOperationsClearAll, newTcellKey(tcell.Key(256), "C", tcell.ModNone), "C",
		"ClearAll",
		"ClearAll",
	)
	k.Transfers.Show = newKeybinding(
		KeyTransfersShow, newTcellKey(tcell.Key(256), "T", tcell.ModNone), "T",
		"Transfers",
		"Transfers",
	)
	k.Transfers.Suspend = newKeybinding(
		KeyTransfersSuspend, newTcellKey(tcell.Key(256), "s", tcell.ModNone), "s",
		"Suspend",
		"Suspend",
	)
	k.Transfers.Resume = newKeybinding(
		KeyTransfersResume, newTcellKey(tcell.Key(256), "r", tcell.ModNone), "r",
		"Resume",
		"Resume",
	)
	k.Transfers.Cancel = newKeybinding(
		KeyTransfersCancel, newTcellKey(tcell.Key(256), "x", tcell.ModNone), "x",
		"Cancel",
		"Cancel",
	)
	k.Log.Show = newKeybinding(
		KeyLogShow, newTcellKey(tcell.Key(256), "L", tcell.ModNone), "L",
		"Transfers",
		"Transfers",
	)
	k.Player.ToggleDisplay = newKeybinding(
		KeyPlayerToggleDisplay, newTcellKey(tcell.Key(256), "M", tcell.ModNone), "M",
		"ToggleDisplay",
		"ToggleDisplay",
	)
	k.Player.ToggleMediaPlaying = newKeybinding(
		KeyPlayerToggleMediaPlaying, newTcellKey(tcell.Key(256), " ", tcell.ModNone), " ",
		"ToggleMediaPlaying",
		"ToggleMediaPlaying",
	)
	k.Player.Next = newKeybinding(
		KeyPlayerNext, newTcellKey(tcell.Key(256), ">", tcell.ModNone), ">",
		"Next",
		"Next",
	)
	k.Player.Previous = newKeybinding(
		KeyPlayerPrevious, newTcellKey(tcell.Key(256), "<", tcell.ModNone), "<",
		"Previous",
		"Previous",
	)
	k.Player.SeekForward = newKeybinding(
		KeyPlayerSeekForward, newTcellKey(tcell.Key(259), "", tcell.ModNone), "right",
		"SeekForward",
		"SeekForward",
	)
	k.Player.SeekBackward = newKeybinding(
		KeyPlayerSeekBackward, newTcellKey(tcell.Key(260), "", tcell.ModNone), "left",
		"SeekBackward",
		"SeekBackward",
	)
	k.Player.Stop = newKeybinding(
		KeyPlayerStop, newTcellKey(tcell.Key(256), "]", tcell.ModNone), "]",
		"Stop",
		"Stop",
	)

	return k
}

type parseKeybindingInfo struct {
	kb     *Keybinding
	cmpCfg string
}

func iterProperties(kb *Keybindings, cfg *Configuration) iter.Seq[parseKeybindingInfo] {
	if cfg == nil {
		cfg = _emptyCmpCfg
	}

	return func(yield func(parseKeybindingInfo) bool) {
		for i := range 52 {
			if !yield(getProperty(kb, cfg, i)) {
				return
			}
		}
	}
}

func getProperty(kb *Keybindings, cfg *Configuration, pos int) parseKeybindingInfo {
	p := parseKeybindingInfo{}

	switch pos {
	case 0:
		p.kb = &kb.SelectItem
		p.cmpCfg = cfg.SelectItem

	case 1:
		p.kb = &kb.CloseItem
		p.cmpCfg = cfg.CloseItem

	case 2:
		p.kb = &kb.FilterItems
		p.cmpCfg = cfg.FilterItems

	case 3:
		p.kb = &kb.Help
		p.cmpCfg = cfg.Help

	case 4:
		p.kb = &kb.Suspend
		p.cmpCfg = cfg.Suspend

	case 5:
		p.kb = &kb.Quit
		p.cmpCfg = cfg.Quit

	case 6:
		p.kb = &kb.NavigateUp
		p.cmpCfg = cfg.NavigateUp

	case 7:
		p.kb = &kb.NavigateDown
		p.cmpCfg = cfg.NavigateDown

	case 8:
		p.kb = &kb.NavigateLeft
		p.cmpCfg = cfg.NavigateLeft

	case 9:
		p.kb = &kb.NavigateRight
		p.cmpCfg = cfg.NavigateRight

	case 10:
		p.kb = &kb.NavigateTop
		p.cmpCfg = cfg.NavigateTop

	case 11:
		p.kb = &kb.NavigateBottom
		p.cmpCfg = cfg.NavigateBottom

	case 12:
		p.kb = &kb.Adapter.TogglePower
		p.cmpCfg = cfg.Adapter.TogglePower

	case 13:
		p.kb = &kb.Adapter.ToggleDiscoverable
		p.cmpCfg = cfg.Adapter.ToggleDiscoverable

	case 14:
		p.kb = &kb.Adapter.TogglePairable
		p.cmpCfg = cfg.Adapter.TogglePairable

	case 15:
		p.kb = &kb.Adapter.ToggleScan
		p.cmpCfg = cfg.Adapter.ToggleScan

	case 16:
		p.kb = &kb.Device.ToggleConnection
		p.cmpCfg = cfg.Device.ToggleConnection

	case 17:
		p.kb = &kb.Device.TogglePairedState
		p.cmpCfg = cfg.Device.TogglePairedState

	case 18:
		p.kb = &kb.Device.Trust
		p.cmpCfg = cfg.Device.Trust

	case 19:
		p.kb = &kb.Device.SendFiles
		p.cmpCfg = cfg.Device.SendFiles

	case 20:
		p.kb = &kb.Device.NetworkOptions
		p.cmpCfg = cfg.Device.NetworkOptions

	case 21:
		p.kb = &kb.Device.AudioProfiles
		p.cmpCfg = cfg.Device.AudioProfiles

	case 22:
		p.kb = &kb.Device.Block
		p.cmpCfg = cfg.Device.Block

	case 23:
		p.kb = &kb.Filebrowser.CdForward
		p.cmpCfg = cfg.Filebrowser.CdForward

	case 24:
		p.kb = &kb.Filebrowser.CdBack
		p.cmpCfg = cfg.Filebrowser.CdBack

	case 25:
		p.kb = &kb.Filebrowser.SelectOne
		p.cmpCfg = cfg.Filebrowser.SelectOne

	case 26:
		p.kb = &kb.Filebrowser.SelectAll
		p.cmpCfg = cfg.Filebrowser.SelectAll

	case 27:
		p.kb = &kb.Filebrowser.InvertSelection
		p.cmpCfg = cfg.Filebrowser.InvertSelection

	case 28:
		p.kb = &kb.Filebrowser.ConfirmSelection
		p.cmpCfg = cfg.Filebrowser.ConfirmSelection

	case 29:
		p.kb = &kb.Filebrowser.Refresh
		p.cmpCfg = cfg.Filebrowser.Refresh

	case 30:
		p.kb = &kb.Filebrowser.ToggleHiddenFiles
		p.cmpCfg = cfg.Filebrowser.ToggleHiddenFiles

	case 31:
		p.kb = &kb.ADTree.ExpandOrSelect
		p.cmpCfg = cfg.ADTree.ExpandOrSelect

	case 32:
		p.kb = &kb.ADTree.TabPane
		p.cmpCfg = cfg.ADTree.TabPane

	case 33:
		p.kb = &kb.TabPane.Next
		p.cmpCfg = cfg.TabPane.Next

	case 34:
		p.kb = &kb.TabPane.Previous
		p.cmpCfg = cfg.TabPane.Previous

	case 35:
		p.kb = &kb.TabPane.ADTree
		p.cmpCfg = cfg.TabPane.ADTree

	case 36:
		p.kb = &kb.Information.Show
		p.cmpCfg = cfg.Information.Show

	case 37:
		p.kb = &kb.Operations.Show
		p.cmpCfg = cfg.Operations.Show

	case 38:
		p.kb = &kb.Operations.Cancel
		p.cmpCfg = cfg.Operations.Cancel

	case 39:
		p.kb = &kb.Operations.ClearAll
		p.cmpCfg = cfg.Operations.ClearAll

	case 40:
		p.kb = &kb.Transfers.Show
		p.cmpCfg = cfg.Transfers.Show

	case 41:
		p.kb = &kb.Transfers.Suspend
		p.cmpCfg = cfg.Transfers.Suspend

	case 42:
		p.kb = &kb.Transfers.Resume
		p.cmpCfg = cfg.Transfers.Resume

	case 43:
		p.kb = &kb.Transfers.Cancel
		p.cmpCfg = cfg.Transfers.Cancel

	case 44:
		p.kb = &kb.Log.Show
		p.cmpCfg = cfg.Log.Show

	case 45:
		p.kb = &kb.Player.ToggleDisplay
		p.cmpCfg = cfg.Player.ToggleDisplay

	case 46:
		p.kb = &kb.Player.ToggleMediaPlaying
		p.cmpCfg = cfg.Player.ToggleMediaPlaying

	case 47:
		p.kb = &kb.Player.Next
		p.cmpCfg = cfg.Player.Next

	case 48:
		p.kb = &kb.Player.Previous
		p.cmpCfg = cfg.Player.Previous

	case 49:
		p.kb = &kb.Player.SeekForward
		p.cmpCfg = cfg.Player.SeekForward

	case 50:
		p.kb = &kb.Player.SeekBackward
		p.cmpCfg = cfg.Player.SeekBackward

	case 51:
		p.kb = &kb.Player.Stop
		p.cmpCfg = cfg.Player.Stop

	}

	return p
}
