// Code generated by structgen. DO NOT EDIT.

package theme

import (
	"iter"

	"github.com/ayn2op/tview"
)

// Theme represents the settings for the app's theme.
type Theme struct {
	Tint string

	Border        tview.Style
	BorderFocused tview.Style

	TitleBar tview.Style
	Global   tview.Style

	ADTree struct {
		Bg tview.Style

		Heading    tview.Style
		Indicators tview.Style
		Selection  tview.Style

		Adapter tview.Style

		Device struct {
			Discovered tview.Style
			Paired     tview.Style
			Unknown    tview.Style
		}

		DevicesList tview.Style

		ActionsList struct {
			Style tview.Style
			Nodes tview.Style
		}
	}

	TabsPane struct {
		Style      tview.Style
		Tab        tview.Style
		FocusedTab tview.Style
	}

	Info struct {
		Style   tview.Style
		Heading tview.Style
	}

	Operations struct {
		Bg      tview.Style
		Heading tview.Style
	}

	Log struct {
		Style tview.Style

		Heading tview.Style
		Time    tview.Style
		Info    tview.Style
		Debug   tview.Style
		Error   tview.Style
	}

	StatusBar struct {
		Style tview.Style
	}
}

var (
	_emptyCmpCfg = &Configuration{}
	_emptyTheme  = &Theme{}
)

func defaultConfig() *RootConfiguration {
	r := &RootConfiguration{}

	r.Tint = "primer"
	r.Border = "bg:from-theme;fg:white"
	r.BorderFocused = "bg:from-theme;fg:green;attr:bold"
	r.TitleBar = "bg:purple;fg:white;attr:bold"
	r.Global = "bg:from-theme;fg:from-theme"
	r.ADTree.Bg = "bg:from-theme"
	r.ADTree.Heading = "bg:from-theme;fg:from-theme"
	r.ADTree.Indicators = "bg:from-theme;fg:from-theme"
	r.ADTree.Selection = "bg:from-theme;fg:blue;attr:reverse"
	r.ADTree.Adapter = "bg:from-theme;fg:from-theme"
	r.ADTree.Device.Discovered = "bg:from-theme;fg:orange"
	r.ADTree.Device.Paired = "bg:from-theme;fg:cyan"
	r.ADTree.Device.Unknown = "bg:from-theme;fg:white"
	r.ADTree.DevicesList = "bg:from-theme;fg:from-theme"
	r.ADTree.ActionsList.Style = "bg:from-theme;fg:from-theme"
	r.ADTree.ActionsList.Nodes = "bg:from-theme;fg:from-theme"
	r.TabsPane.Style = "bg:from-theme;fg:from-theme"
	r.TabsPane.Tab = "bg:from-theme;fg:from-theme"
	r.TabsPane.FocusedTab = "bg:from-theme;fg:brightcyan;attr:bold,underline"
	r.Info.Style = "bg:from-theme;fg:white"
	r.Info.Heading = "bg:from-theme;fg:from-theme"
	r.Operations.Bg = "bg:blue"
	r.Operations.Heading = "bg:from-theme;fg:from-theme"
	r.Log.Style = "bg:from-theme;fg:from-theme"
	r.Log.Heading = "bg:from-theme;fg:from-theme"
	r.Log.Time = "bg:from-theme;fg:brightblack(lighten:0.1)"
	r.Log.Info = "bg:from-theme;fg:blue(lighten:0.2);attr:bold"
	r.Log.Debug = "bg:from-theme;fg:brightpurple;attr:bold,underline"
	r.Log.Error = "bg:from-theme;fg:red;attr:bold,underline"
	r.StatusBar.Style = "bg:purple;fg:white;attr:bold"

	return r
}

// parseThemeInfo holds the theme parsing information.
type parseThemeInfo struct {
	rootCfg *string
	cmpCfg  string

	style *tview.Style
}

// iterProperties iterates over the configuration's and theme's properties.
func iterProperties(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme) iter.Seq[parseThemeInfo] {
	if cmpCfg == nil {
		cmpCfg = _emptyCmpCfg
	}

	if t == nil {
		t = _emptyTheme
	}

	return func(yield func(parseThemeInfo) bool) {
		for i := range 29 {
			if !yield(getProperty(cfg, cmpCfg, t, i)) {
				return
			}
		}
	}
}

// getProperty returns the property according to the specified parsing position.
func getProperty(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme, pos int) parseThemeInfo {
	p := parseThemeInfo{}

	switch pos {
	case 0:
		p.rootCfg = &cfg.Border
		p.cmpCfg = cmpCfg.Border
		p.style = &t.Border

	case 1:
		p.rootCfg = &cfg.BorderFocused
		p.cmpCfg = cmpCfg.BorderFocused
		p.style = &t.BorderFocused

	case 2:
		p.rootCfg = &cfg.TitleBar
		p.cmpCfg = cmpCfg.TitleBar
		p.style = &t.TitleBar

	case 3:
		p.rootCfg = &cfg.Global
		p.cmpCfg = cmpCfg.Global
		p.style = &t.Global

	case 4:
		p.rootCfg = &cfg.ADTree.Bg
		p.cmpCfg = cmpCfg.ADTree.Bg
		p.style = &t.ADTree.Bg

	case 5:
		p.rootCfg = &cfg.ADTree.Heading
		p.cmpCfg = cmpCfg.ADTree.Heading
		p.style = &t.ADTree.Heading

	case 6:
		p.rootCfg = &cfg.ADTree.Indicators
		p.cmpCfg = cmpCfg.ADTree.Indicators
		p.style = &t.ADTree.Indicators

	case 7:
		p.rootCfg = &cfg.ADTree.Selection
		p.cmpCfg = cmpCfg.ADTree.Selection
		p.style = &t.ADTree.Selection

	case 8:
		p.rootCfg = &cfg.ADTree.Adapter
		p.cmpCfg = cmpCfg.ADTree.Adapter
		p.style = &t.ADTree.Adapter

	case 9:
		p.rootCfg = &cfg.ADTree.Device.Discovered
		p.cmpCfg = cmpCfg.ADTree.Device.Discovered
		p.style = &t.ADTree.Device.Discovered

	case 10:
		p.rootCfg = &cfg.ADTree.Device.Paired
		p.cmpCfg = cmpCfg.ADTree.Device.Paired
		p.style = &t.ADTree.Device.Paired

	case 11:
		p.rootCfg = &cfg.ADTree.Device.Unknown
		p.cmpCfg = cmpCfg.ADTree.Device.Unknown
		p.style = &t.ADTree.Device.Unknown

	case 12:
		p.rootCfg = &cfg.ADTree.DevicesList
		p.cmpCfg = cmpCfg.ADTree.DevicesList
		p.style = &t.ADTree.DevicesList

	case 13:
		p.rootCfg = &cfg.ADTree.ActionsList.Style
		p.cmpCfg = cmpCfg.ADTree.ActionsList.Style
		p.style = &t.ADTree.ActionsList.Style

	case 14:
		p.rootCfg = &cfg.ADTree.ActionsList.Nodes
		p.cmpCfg = cmpCfg.ADTree.ActionsList.Nodes
		p.style = &t.ADTree.ActionsList.Nodes

	case 15:
		p.rootCfg = &cfg.TabsPane.Style
		p.cmpCfg = cmpCfg.TabsPane.Style
		p.style = &t.TabsPane.Style

	case 16:
		p.rootCfg = &cfg.TabsPane.Tab
		p.cmpCfg = cmpCfg.TabsPane.Tab
		p.style = &t.TabsPane.Tab

	case 17:
		p.rootCfg = &cfg.TabsPane.FocusedTab
		p.cmpCfg = cmpCfg.TabsPane.FocusedTab
		p.style = &t.TabsPane.FocusedTab

	case 18:
		p.rootCfg = &cfg.Info.Style
		p.cmpCfg = cmpCfg.Info.Style
		p.style = &t.Info.Style

	case 19:
		p.rootCfg = &cfg.Info.Heading
		p.cmpCfg = cmpCfg.Info.Heading
		p.style = &t.Info.Heading

	case 20:
		p.rootCfg = &cfg.Operations.Bg
		p.cmpCfg = cmpCfg.Operations.Bg
		p.style = &t.Operations.Bg

	case 21:
		p.rootCfg = &cfg.Operations.Heading
		p.cmpCfg = cmpCfg.Operations.Heading
		p.style = &t.Operations.Heading

	case 22:
		p.rootCfg = &cfg.Log.Style
		p.cmpCfg = cmpCfg.Log.Style
		p.style = &t.Log.Style

	case 23:
		p.rootCfg = &cfg.Log.Heading
		p.cmpCfg = cmpCfg.Log.Heading
		p.style = &t.Log.Heading

	case 24:
		p.rootCfg = &cfg.Log.Time
		p.cmpCfg = cmpCfg.Log.Time
		p.style = &t.Log.Time

	case 25:
		p.rootCfg = &cfg.Log.Info
		p.cmpCfg = cmpCfg.Log.Info
		p.style = &t.Log.Info

	case 26:
		p.rootCfg = &cfg.Log.Debug
		p.cmpCfg = cmpCfg.Log.Debug
		p.style = &t.Log.Debug

	case 27:
		p.rootCfg = &cfg.Log.Error
		p.cmpCfg = cmpCfg.Log.Error
		p.style = &t.Log.Error

	case 28:
		p.rootCfg = &cfg.StatusBar.Style
		p.cmpCfg = cmpCfg.StatusBar.Style
		p.style = &t.StatusBar.Style

	}

	return p
}
