// Code generated by structgen. DO NOT EDIT.

package theme

import (
	"iter"

	"charm.land/lipgloss/v2"
)

// Theme represents the settings for the app's theme.
type Theme struct {
	Tint string

	Border        lipgloss.Style
	BorderFocused lipgloss.Style

	TitleBar lipgloss.Style

	ADTree struct {
		Headers lipgloss.Style

		ExpandedIndicator lipgloss.Style
		ClosedIndicator   lipgloss.Style
		Selection         lipgloss.Style

		Adapter struct {
			Present lipgloss.Style
		}

		Device struct {
			Discovered lipgloss.Style
			Paired     lipgloss.Style
		}

		DevicesList struct {
			Nodes lipgloss.Style
		}

		ActionsList struct {
			Nodes lipgloss.Style
		}
	}

	TabsPane struct {
		Style      lipgloss.Style
		Tab        lipgloss.Style
		FocusedTab lipgloss.Style
	}

	Info struct {
		Style   lipgloss.Style
		Heading lipgloss.Style
	}

	Operations struct {
		Style   lipgloss.Style
		Heading lipgloss.Style
	}

	Log struct {
		Style   lipgloss.Style
		Heading lipgloss.Style

		Time  lipgloss.Style
		Info  lipgloss.Style
		Debug lipgloss.Style
		Error lipgloss.Style
	}

	StatusBar struct {
		Style lipgloss.Style
	}
}

var (
	_emptyCmpCfg = &Configuration{}
	_emptyTheme  = &Theme{}
)

func defaultConfig() *RootConfiguration {
	r := &RootConfiguration{}

	r.Tint = "primer"
	r.Border = "bg:from-theme;fg:white"
	r.BorderFocused = "bg:from-theme;fg:green;attr:bold"
	r.TitleBar = "bg:purple;fg:white;attr:bold"
	r.ADTree.Headers = "bg:from-theme;fg:from-theme"
	r.ADTree.ExpandedIndicator = "bg:from-theme;fg:from-theme"
	r.ADTree.ClosedIndicator = "bg:from-theme;fg:from-theme"
	r.ADTree.Selection = "bg:from-theme;fg:blue;attr:reverse"
	r.ADTree.Adapter.Present = "bg:from-theme;fg:from-theme"
	r.ADTree.Device.Discovered = "bg:from-theme;fg:from-theme"
	r.ADTree.Device.Paired = "bg:from-theme;fg:from-theme"
	r.ADTree.DevicesList.Nodes = "bg:from-theme;fg:from-theme"
	r.ADTree.ActionsList.Nodes = "bg:from-theme;fg:from-theme"
	r.TabsPane.Style = "bg:from-theme;fg:from-theme"
	r.TabsPane.Tab = "bg:from-theme;fg:from-theme"
	r.TabsPane.FocusedTab = "bg:from-theme;fg:brightcyan"
	r.Info.Style = "bg:blue;fg:white"
	r.Info.Heading = "bg:from-theme;fg:from-theme"
	r.Operations.Style = "bg:blue;fg:white"
	r.Operations.Heading = "bg:from-theme;fg:from-theme"
	r.Log.Style = "bg:from-theme;fg:from-theme"
	r.Log.Heading = "bg:from-theme;fg:from-theme"
	r.Log.Time = "bg:from-theme;fg:brightblack(lighten:0.1)"
	r.Log.Info = "bg:from-theme;fg:blue(lighten:0.2);attr:bold"
	r.Log.Debug = "bg:from-theme;fg:brightpurple;attr:bold,underline"
	r.Log.Error = "bg:from-theme;fg:red;attr:bold,underline"
	r.StatusBar.Style = "bg:purple;fg:white;attr:bold"

	return r
}

// parseThemeInfo holds the theme parsing information.
type parseThemeInfo struct {
	rootCfg *string
	cmpCfg  string

	style *lipgloss.Style
}

// iterProperties iterates over the configuration's and theme's properties.
func iterProperties(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme) iter.Seq[parseThemeInfo] {
	if cmpCfg == nil {
		cmpCfg = _emptyCmpCfg
	}

	if t == nil {
		t = _emptyTheme
	}

	return func(yield func(parseThemeInfo) bool) {
		for i := range 26 {
			if !yield(getProperty(cfg, cmpCfg, t, i)) {
				return
			}
		}
	}
}

// getProperty returns the property according to the specified parsing position.
func getProperty(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme, pos int) parseThemeInfo {
	p := parseThemeInfo{}

	switch pos {
	case 0:
		p.rootCfg = &cfg.Border
		p.cmpCfg = cmpCfg.Border
		p.style = &t.Border

	case 1:
		p.rootCfg = &cfg.BorderFocused
		p.cmpCfg = cmpCfg.BorderFocused
		p.style = &t.BorderFocused

	case 2:
		p.rootCfg = &cfg.TitleBar
		p.cmpCfg = cmpCfg.TitleBar
		p.style = &t.TitleBar

	case 3:
		p.rootCfg = &cfg.ADTree.Headers
		p.cmpCfg = cmpCfg.ADTree.Headers
		p.style = &t.ADTree.Headers

	case 4:
		p.rootCfg = &cfg.ADTree.ExpandedIndicator
		p.cmpCfg = cmpCfg.ADTree.ExpandedIndicator
		p.style = &t.ADTree.ExpandedIndicator

	case 5:
		p.rootCfg = &cfg.ADTree.ClosedIndicator
		p.cmpCfg = cmpCfg.ADTree.ClosedIndicator
		p.style = &t.ADTree.ClosedIndicator

	case 6:
		p.rootCfg = &cfg.ADTree.Selection
		p.cmpCfg = cmpCfg.ADTree.Selection
		p.style = &t.ADTree.Selection

	case 7:
		p.rootCfg = &cfg.ADTree.Adapter.Present
		p.cmpCfg = cmpCfg.ADTree.Adapter.Present
		p.style = &t.ADTree.Adapter.Present

	case 8:
		p.rootCfg = &cfg.ADTree.Device.Discovered
		p.cmpCfg = cmpCfg.ADTree.Device.Discovered
		p.style = &t.ADTree.Device.Discovered

	case 9:
		p.rootCfg = &cfg.ADTree.Device.Paired
		p.cmpCfg = cmpCfg.ADTree.Device.Paired
		p.style = &t.ADTree.Device.Paired

	case 10:
		p.rootCfg = &cfg.ADTree.DevicesList.Nodes
		p.cmpCfg = cmpCfg.ADTree.DevicesList.Nodes
		p.style = &t.ADTree.DevicesList.Nodes

	case 11:
		p.rootCfg = &cfg.ADTree.ActionsList.Nodes
		p.cmpCfg = cmpCfg.ADTree.ActionsList.Nodes
		p.style = &t.ADTree.ActionsList.Nodes

	case 12:
		p.rootCfg = &cfg.TabsPane.Style
		p.cmpCfg = cmpCfg.TabsPane.Style
		p.style = &t.TabsPane.Style

	case 13:
		p.rootCfg = &cfg.TabsPane.Tab
		p.cmpCfg = cmpCfg.TabsPane.Tab
		p.style = &t.TabsPane.Tab

	case 14:
		p.rootCfg = &cfg.TabsPane.FocusedTab
		p.cmpCfg = cmpCfg.TabsPane.FocusedTab
		p.style = &t.TabsPane.FocusedTab

	case 15:
		p.rootCfg = &cfg.Info.Style
		p.cmpCfg = cmpCfg.Info.Style
		p.style = &t.Info.Style

	case 16:
		p.rootCfg = &cfg.Info.Heading
		p.cmpCfg = cmpCfg.Info.Heading
		p.style = &t.Info.Heading

	case 17:
		p.rootCfg = &cfg.Operations.Style
		p.cmpCfg = cmpCfg.Operations.Style
		p.style = &t.Operations.Style

	case 18:
		p.rootCfg = &cfg.Operations.Heading
		p.cmpCfg = cmpCfg.Operations.Heading
		p.style = &t.Operations.Heading

	case 19:
		p.rootCfg = &cfg.Log.Style
		p.cmpCfg = cmpCfg.Log.Style
		p.style = &t.Log.Style

	case 20:
		p.rootCfg = &cfg.Log.Heading
		p.cmpCfg = cmpCfg.Log.Heading
		p.style = &t.Log.Heading

	case 21:
		p.rootCfg = &cfg.Log.Time
		p.cmpCfg = cmpCfg.Log.Time
		p.style = &t.Log.Time

	case 22:
		p.rootCfg = &cfg.Log.Info
		p.cmpCfg = cmpCfg.Log.Info
		p.style = &t.Log.Info

	case 23:
		p.rootCfg = &cfg.Log.Debug
		p.cmpCfg = cmpCfg.Log.Debug
		p.style = &t.Log.Debug

	case 24:
		p.rootCfg = &cfg.Log.Error
		p.cmpCfg = cmpCfg.Log.Error
		p.style = &t.Log.Error

	case 25:
		p.rootCfg = &cfg.StatusBar.Style
		p.cmpCfg = cmpCfg.StatusBar.Style
		p.style = &t.StatusBar.Style

	}

	return p
}
