// Code generated by structgen. DO NOT EDIT.

package theme

import (
	"iter"

	"github.com/ayn2op/tview"
)

// Theme represents the settings for the app's theme.
type Theme struct {
	Tint string

	Global tview.Style

	App struct {
		TitleBar tview.Style

		Border        tview.Style
		BorderFocused tview.Style
	}

	ADTree struct {
		Title      tview.Style
		Indicators tview.Style
		Selection  tview.Style

		Adapter tview.Style

		Device struct {
			Discovered tview.Style
			Paired     tview.Style
			Unknown    tview.Style
		}

		DevicesList tview.Style

		ActionsList struct {
			Style tview.Style
			Nodes tview.Style
		}
	}

	TabsPane struct {
		Style      tview.Style
		Tab        tview.Style
		FocusedTab tview.Style
	}

	Info struct {
		Style tview.Style
		Title tview.Style
	}

	Operations struct {
		Title     tview.Style
		Selection tview.Style

		OperationNumber tview.Style
		PropertyName    tview.Style
		Error           tview.Style
		Completed       tview.Style
		InProgress      tview.Style
		Message         tview.Style
	}

	Log struct {
		Title tview.Style
		Time  tview.Style
		Info  tview.Style
		Debug tview.Style
		Error tview.Style
	}

	StatusBar struct {
		Style tview.Style
	}
}

var (
	_emptyCmpCfg = &Configuration{}
	_emptyTheme  = &Theme{}
)

func defaultConfig() *RootConfiguration {
	r := &RootConfiguration{}

	r.Tint = "primer"
	r.Global = "bg:from-theme;fg:from-theme"
	r.App.TitleBar = "bg:purple;fg:white;attr:bold"
	r.App.Border = "bg:from-theme;fg:white"
	r.App.BorderFocused = "bg:from-theme;fg:green;attr:bold"
	r.ADTree.Title = "bg:from-theme;fg:from-theme"
	r.ADTree.Indicators = "bg:from-theme;fg:from-theme"
	r.ADTree.Selection = "bg:from-theme;fg:blue;attr:reverse"
	r.ADTree.Adapter = "bg:from-theme;fg:from-theme"
	r.ADTree.Device.Discovered = "bg:from-theme;fg:orange"
	r.ADTree.Device.Paired = "bg:from-theme;fg:cyan"
	r.ADTree.Device.Unknown = "bg:from-theme;fg:white"
	r.ADTree.DevicesList = "bg:from-theme;fg:from-theme"
	r.ADTree.ActionsList.Style = "bg:from-theme;fg:from-theme"
	r.ADTree.ActionsList.Nodes = "bg:from-theme;fg:from-theme"
	r.TabsPane.Style = "bg:from-theme;fg:from-theme"
	r.TabsPane.Tab = "bg:from-theme;fg:from-theme"
	r.TabsPane.FocusedTab = "bg:from-theme;fg:brightcyan;attr:bold,underline"
	r.Info.Style = "bg:from-theme;fg:white"
	r.Info.Title = "bg:from-theme;fg:from-theme"
	r.Operations.Title = "bg:from-theme;fg:from-theme"
	r.Operations.Selection = "bg:from-theme;fg:blue"
	r.Operations.OperationNumber = "bg:from-theme;fg:brightpurple;attr:bold,italic,underline"
	r.Operations.PropertyName = "bg:from-theme;fg:brightpurple;attr:bold,underline"
	r.Operations.Error = "bg:from-theme;fg:red;attr:bold"
	r.Operations.Completed = "bg:from-theme;fg:green"
	r.Operations.InProgress = "bg:from-theme;fg:yellow"
	r.Operations.Message = "bg:from-theme;fg:white;attr:bold"
	r.Log.Title = "bg:from-theme;fg:from-theme"
	r.Log.Time = "bg:from-theme;fg:brightblack(lighten:0.1)"
	r.Log.Info = "bg:from-theme;fg:blue(lighten:0.2);attr:bold"
	r.Log.Debug = "bg:from-theme;fg:brightpurple;attr:bold,underline"
	r.Log.Error = "bg:from-theme;fg:red;attr:bold,underline"
	r.StatusBar.Style = "bg:purple;fg:white;attr:bold"

	return r
}

// parseThemeInfo holds the theme parsing information.
type parseThemeInfo struct {
	rootCfg *string
	cmpCfg  string

	style *tview.Style
}

// iterProperties iterates over the configuration's and theme's properties.
func iterProperties(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme) iter.Seq[parseThemeInfo] {
	if cmpCfg == nil {
		cmpCfg = _emptyCmpCfg
	}

	if t == nil {
		t = _emptyTheme
	}

	return func(yield func(parseThemeInfo) bool) {
		for i := range 33 {
			if !yield(getProperty(cfg, cmpCfg, t, i)) {
				return
			}
		}
	}
}

// getProperty returns the property according to the specified parsing position.
func getProperty(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme, pos int) parseThemeInfo {
	p := parseThemeInfo{}

	switch pos {
	case 0:
		p.rootCfg = &cfg.Global
		p.cmpCfg = cmpCfg.Global
		p.style = &t.Global

	case 1:
		p.rootCfg = &cfg.App.TitleBar
		p.cmpCfg = cmpCfg.App.TitleBar
		p.style = &t.App.TitleBar

	case 2:
		p.rootCfg = &cfg.App.Border
		p.cmpCfg = cmpCfg.App.Border
		p.style = &t.App.Border

	case 3:
		p.rootCfg = &cfg.App.BorderFocused
		p.cmpCfg = cmpCfg.App.BorderFocused
		p.style = &t.App.BorderFocused

	case 4:
		p.rootCfg = &cfg.ADTree.Title
		p.cmpCfg = cmpCfg.ADTree.Title
		p.style = &t.ADTree.Title

	case 5:
		p.rootCfg = &cfg.ADTree.Indicators
		p.cmpCfg = cmpCfg.ADTree.Indicators
		p.style = &t.ADTree.Indicators

	case 6:
		p.rootCfg = &cfg.ADTree.Selection
		p.cmpCfg = cmpCfg.ADTree.Selection
		p.style = &t.ADTree.Selection

	case 7:
		p.rootCfg = &cfg.ADTree.Adapter
		p.cmpCfg = cmpCfg.ADTree.Adapter
		p.style = &t.ADTree.Adapter

	case 8:
		p.rootCfg = &cfg.ADTree.Device.Discovered
		p.cmpCfg = cmpCfg.ADTree.Device.Discovered
		p.style = &t.ADTree.Device.Discovered

	case 9:
		p.rootCfg = &cfg.ADTree.Device.Paired
		p.cmpCfg = cmpCfg.ADTree.Device.Paired
		p.style = &t.ADTree.Device.Paired

	case 10:
		p.rootCfg = &cfg.ADTree.Device.Unknown
		p.cmpCfg = cmpCfg.ADTree.Device.Unknown
		p.style = &t.ADTree.Device.Unknown

	case 11:
		p.rootCfg = &cfg.ADTree.DevicesList
		p.cmpCfg = cmpCfg.ADTree.DevicesList
		p.style = &t.ADTree.DevicesList

	case 12:
		p.rootCfg = &cfg.ADTree.ActionsList.Style
		p.cmpCfg = cmpCfg.ADTree.ActionsList.Style
		p.style = &t.ADTree.ActionsList.Style

	case 13:
		p.rootCfg = &cfg.ADTree.ActionsList.Nodes
		p.cmpCfg = cmpCfg.ADTree.ActionsList.Nodes
		p.style = &t.ADTree.ActionsList.Nodes

	case 14:
		p.rootCfg = &cfg.TabsPane.Style
		p.cmpCfg = cmpCfg.TabsPane.Style
		p.style = &t.TabsPane.Style

	case 15:
		p.rootCfg = &cfg.TabsPane.Tab
		p.cmpCfg = cmpCfg.TabsPane.Tab
		p.style = &t.TabsPane.Tab

	case 16:
		p.rootCfg = &cfg.TabsPane.FocusedTab
		p.cmpCfg = cmpCfg.TabsPane.FocusedTab
		p.style = &t.TabsPane.FocusedTab

	case 17:
		p.rootCfg = &cfg.Info.Style
		p.cmpCfg = cmpCfg.Info.Style
		p.style = &t.Info.Style

	case 18:
		p.rootCfg = &cfg.Info.Title
		p.cmpCfg = cmpCfg.Info.Title
		p.style = &t.Info.Title

	case 19:
		p.rootCfg = &cfg.Operations.Title
		p.cmpCfg = cmpCfg.Operations.Title
		p.style = &t.Operations.Title

	case 20:
		p.rootCfg = &cfg.Operations.Selection
		p.cmpCfg = cmpCfg.Operations.Selection
		p.style = &t.Operations.Selection

	case 21:
		p.rootCfg = &cfg.Operations.OperationNumber
		p.cmpCfg = cmpCfg.Operations.OperationNumber
		p.style = &t.Operations.OperationNumber

	case 22:
		p.rootCfg = &cfg.Operations.PropertyName
		p.cmpCfg = cmpCfg.Operations.PropertyName
		p.style = &t.Operations.PropertyName

	case 23:
		p.rootCfg = &cfg.Operations.Error
		p.cmpCfg = cmpCfg.Operations.Error
		p.style = &t.Operations.Error

	case 24:
		p.rootCfg = &cfg.Operations.Completed
		p.cmpCfg = cmpCfg.Operations.Completed
		p.style = &t.Operations.Completed

	case 25:
		p.rootCfg = &cfg.Operations.InProgress
		p.cmpCfg = cmpCfg.Operations.InProgress
		p.style = &t.Operations.InProgress

	case 26:
		p.rootCfg = &cfg.Operations.Message
		p.cmpCfg = cmpCfg.Operations.Message
		p.style = &t.Operations.Message

	case 27:
		p.rootCfg = &cfg.Log.Title
		p.cmpCfg = cmpCfg.Log.Title
		p.style = &t.Log.Title

	case 28:
		p.rootCfg = &cfg.Log.Time
		p.cmpCfg = cmpCfg.Log.Time
		p.style = &t.Log.Time

	case 29:
		p.rootCfg = &cfg.Log.Info
		p.cmpCfg = cmpCfg.Log.Info
		p.style = &t.Log.Info

	case 30:
		p.rootCfg = &cfg.Log.Debug
		p.cmpCfg = cmpCfg.Log.Debug
		p.style = &t.Log.Debug

	case 31:
		p.rootCfg = &cfg.Log.Error
		p.cmpCfg = cmpCfg.Log.Error
		p.style = &t.Log.Error

	case 32:
		p.rootCfg = &cfg.StatusBar.Style
		p.cmpCfg = cmpCfg.StatusBar.Style
		p.style = &t.StatusBar.Style

	}

	return p
}
