// Code generated by structgen. DO NOT EDIT.

package theme

import (
	"iter"

	"github.com/gdamore/tcell/v3"
)

// Theme represents the settings for the app's theme.
type Theme struct {
	Tint string

	Global tcell.Style

	App struct {
		TitleBar tcell.Style

		Border        tcell.Style
		BorderFocused tcell.Style

		PlaceHolder tcell.Style
	}

	ADTree struct {
		Title      tcell.Style
		Indicators tcell.Style
		Selection  tcell.Style

		Adapter struct {
			Name tcell.Style

			PoweredOnPill    tcell.Style
			PoweredOffPill   tcell.Style
			DiscoverablePill tcell.Style
			ScanningPill     tcell.Style
			PairablePill     tcell.Style
		}

		Device struct {
			Discovered tcell.Style
			Paired     tcell.Style
			Unknown    tcell.Style

			NewDevicePill tcell.Style
			PairedPill    tcell.Style
			TrustedPill   tcell.Style
			ConnectedPill tcell.Style
			BlockedPill   tcell.Style
		}

		DevicesList tcell.Style

		ActionsList struct {
			Style tcell.Style
			Nodes tcell.Style
		}

		Status tcell.Style
	}

	TabsPane struct {
		ArrowStyle tcell.Style
		Tab        tcell.Style
		FocusedTab tcell.Style
	}

	Info struct {
		Title         tcell.Style
		PropertyName  tcell.Style
		PropertyValue tcell.Style
	}

	Operations struct {
		Title     tcell.Style
		Selection tcell.Style

		OperationNumber tcell.Style
		Time            tcell.Style
		PropertyName    tcell.Style
		Error           tcell.Style
		Completed       tcell.Style
		InProgress      tcell.Style
		Message         tcell.Style
	}

	Log struct {
		Title tcell.Style
		Time  tcell.Style
		Info  tcell.Style
		Debug tcell.Style
		Error tcell.Style
	}

	StatusBar struct {
		Style tcell.Style
	}
}

var (
	_emptyCmpCfg = &Configuration{}
	_emptyTheme  = &Theme{}
)

func defaultConfig() *RootConfiguration {
	r := &RootConfiguration{}

	r.Tint = "primer"
	r.Global = "bg:from-theme;fg:from-theme"
	r.App.TitleBar = "bg:purple;fg:white;attr:bold"
	r.App.Border = "bg:from-theme;fg:white"
	r.App.BorderFocused = "bg:from-theme;fg:green;attr:bold"
	r.App.PlaceHolder = "bg:from-theme;fg:grey;attr:italic"
	r.ADTree.Title = "bg:from-theme;fg:from-theme"
	r.ADTree.Indicators = "bg:from-theme;fg:from-theme"
	r.ADTree.Selection = "bg:from-theme;fg:blue;attr:reverse"
	r.ADTree.Adapter.Name = "bg:from-theme;fg:from-theme"
	r.ADTree.Adapter.PoweredOnPill = "bg:green;fg:black"
	r.ADTree.Adapter.PoweredOffPill = "bg:red;fg:white"
	r.ADTree.Adapter.DiscoverablePill = "bg:blue;fg:white"
	r.ADTree.Adapter.ScanningPill = "bg:yellow;fg:black"
	r.ADTree.Adapter.PairablePill = "bg:cyan;fg:black"
	r.ADTree.Device.Discovered = "bg:from-theme;fg:orange"
	r.ADTree.Device.Paired = "bg:from-theme;fg:cyan"
	r.ADTree.Device.Unknown = "bg:from-theme;fg:white"
	r.ADTree.Device.NewDevicePill = "bg:orange;fg:black"
	r.ADTree.Device.PairedPill = "bg:cyan;fg:black"
	r.ADTree.Device.TrustedPill = "bg:purple;fg:white"
	r.ADTree.Device.ConnectedPill = "bg:green;fg:black"
	r.ADTree.Device.BlockedPill = "bg:red;fg:white"
	r.ADTree.DevicesList = "bg:from-theme;fg:from-theme"
	r.ADTree.ActionsList.Style = "bg:from-theme;fg:from-theme"
	r.ADTree.ActionsList.Nodes = "bg:from-theme;fg:from-theme"
	r.ADTree.Status = "bg:from-theme;fg:from-theme"
	r.TabsPane.ArrowStyle = "bg:from-theme;fg:from-theme"
	r.TabsPane.Tab = "bg:from-theme;fg:from-theme"
	r.TabsPane.FocusedTab = "bg:from-theme;fg:brightcyan;attr:bold,underline"
	r.Info.Title = "bg:purple;fg:white"
	r.Info.PropertyName = "bg:from-theme;fg:brightpurple;attr:bold"
	r.Info.PropertyValue = "bg:from-theme;fg:white"
	r.Operations.Title = "bg:from-theme;fg:from-theme"
	r.Operations.Selection = "bg:from-theme;fg:blue"
	r.Operations.OperationNumber = "bg:from-theme;fg:brightpurple;attr:bold,italic,underline"
	r.Operations.Time = "bg:from-theme;fg:grey;attr:italic"
	r.Operations.PropertyName = "bg:from-theme;fg:brightpurple;attr:bold,underline"
	r.Operations.Error = "bg:from-theme;fg:red;attr:bold"
	r.Operations.Completed = "bg:from-theme;fg:green"
	r.Operations.InProgress = "bg:from-theme;fg:yellow"
	r.Operations.Message = "bg:from-theme;fg:white;attr:bold"
	r.Log.Title = "bg:from-theme;fg:from-theme"
	r.Log.Time = "bg:from-theme;fg:brightblack(lighten:0.1)"
	r.Log.Info = "bg:from-theme;fg:blue(lighten:0.2);attr:bold"
	r.Log.Debug = "bg:from-theme;fg:brightpurple;attr:bold,underline"
	r.Log.Error = "bg:from-theme;fg:red;attr:bold,underline"
	r.StatusBar.Style = "bg:purple;fg:white;attr:bold"

	return r
}

// parseThemeInfo holds the theme parsing information.
type parseThemeInfo struct {
	rootCfg *string
	cmpCfg  string

	style *tcell.Style
}

// iterProperties iterates over the configuration's and theme's properties.
func iterProperties(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme) iter.Seq[parseThemeInfo] {
	if cmpCfg == nil {
		cmpCfg = _emptyCmpCfg
	}

	if t == nil {
		t = _emptyTheme
	}

	return func(yield func(parseThemeInfo) bool) {
		for i := range 47 {
			if !yield(getProperty(cfg, cmpCfg, t, i)) {
				return
			}
		}
	}
}

// getProperty returns the property according to the specified parsing position.
func getProperty(cfg *RootConfiguration, cmpCfg *Configuration, t *Theme, pos int) parseThemeInfo {
	p := parseThemeInfo{}

	switch pos {
	case 0:
		p.rootCfg = &cfg.Global
		p.cmpCfg = cmpCfg.Global
		p.style = &t.Global

	case 1:
		p.rootCfg = &cfg.App.TitleBar
		p.cmpCfg = cmpCfg.App.TitleBar
		p.style = &t.App.TitleBar

	case 2:
		p.rootCfg = &cfg.App.Border
		p.cmpCfg = cmpCfg.App.Border
		p.style = &t.App.Border

	case 3:
		p.rootCfg = &cfg.App.BorderFocused
		p.cmpCfg = cmpCfg.App.BorderFocused
		p.style = &t.App.BorderFocused

	case 4:
		p.rootCfg = &cfg.App.PlaceHolder
		p.cmpCfg = cmpCfg.App.PlaceHolder
		p.style = &t.App.PlaceHolder

	case 5:
		p.rootCfg = &cfg.ADTree.Title
		p.cmpCfg = cmpCfg.ADTree.Title
		p.style = &t.ADTree.Title

	case 6:
		p.rootCfg = &cfg.ADTree.Indicators
		p.cmpCfg = cmpCfg.ADTree.Indicators
		p.style = &t.ADTree.Indicators

	case 7:
		p.rootCfg = &cfg.ADTree.Selection
		p.cmpCfg = cmpCfg.ADTree.Selection
		p.style = &t.ADTree.Selection

	case 8:
		p.rootCfg = &cfg.ADTree.Adapter.Name
		p.cmpCfg = cmpCfg.ADTree.Adapter.Name
		p.style = &t.ADTree.Adapter.Name

	case 9:
		p.rootCfg = &cfg.ADTree.Adapter.PoweredOnPill
		p.cmpCfg = cmpCfg.ADTree.Adapter.PoweredOnPill
		p.style = &t.ADTree.Adapter.PoweredOnPill

	case 10:
		p.rootCfg = &cfg.ADTree.Adapter.PoweredOffPill
		p.cmpCfg = cmpCfg.ADTree.Adapter.PoweredOffPill
		p.style = &t.ADTree.Adapter.PoweredOffPill

	case 11:
		p.rootCfg = &cfg.ADTree.Adapter.DiscoverablePill
		p.cmpCfg = cmpCfg.ADTree.Adapter.DiscoverablePill
		p.style = &t.ADTree.Adapter.DiscoverablePill

	case 12:
		p.rootCfg = &cfg.ADTree.Adapter.ScanningPill
		p.cmpCfg = cmpCfg.ADTree.Adapter.ScanningPill
		p.style = &t.ADTree.Adapter.ScanningPill

	case 13:
		p.rootCfg = &cfg.ADTree.Adapter.PairablePill
		p.cmpCfg = cmpCfg.ADTree.Adapter.PairablePill
		p.style = &t.ADTree.Adapter.PairablePill

	case 14:
		p.rootCfg = &cfg.ADTree.Device.Discovered
		p.cmpCfg = cmpCfg.ADTree.Device.Discovered
		p.style = &t.ADTree.Device.Discovered

	case 15:
		p.rootCfg = &cfg.ADTree.Device.Paired
		p.cmpCfg = cmpCfg.ADTree.Device.Paired
		p.style = &t.ADTree.Device.Paired

	case 16:
		p.rootCfg = &cfg.ADTree.Device.Unknown
		p.cmpCfg = cmpCfg.ADTree.Device.Unknown
		p.style = &t.ADTree.Device.Unknown

	case 17:
		p.rootCfg = &cfg.ADTree.Device.NewDevicePill
		p.cmpCfg = cmpCfg.ADTree.Device.NewDevicePill
		p.style = &t.ADTree.Device.NewDevicePill

	case 18:
		p.rootCfg = &cfg.ADTree.Device.PairedPill
		p.cmpCfg = cmpCfg.ADTree.Device.PairedPill
		p.style = &t.ADTree.Device.PairedPill

	case 19:
		p.rootCfg = &cfg.ADTree.Device.TrustedPill
		p.cmpCfg = cmpCfg.ADTree.Device.TrustedPill
		p.style = &t.ADTree.Device.TrustedPill

	case 20:
		p.rootCfg = &cfg.ADTree.Device.ConnectedPill
		p.cmpCfg = cmpCfg.ADTree.Device.ConnectedPill
		p.style = &t.ADTree.Device.ConnectedPill

	case 21:
		p.rootCfg = &cfg.ADTree.Device.BlockedPill
		p.cmpCfg = cmpCfg.ADTree.Device.BlockedPill
		p.style = &t.ADTree.Device.BlockedPill

	case 22:
		p.rootCfg = &cfg.ADTree.DevicesList
		p.cmpCfg = cmpCfg.ADTree.DevicesList
		p.style = &t.ADTree.DevicesList

	case 23:
		p.rootCfg = &cfg.ADTree.ActionsList.Style
		p.cmpCfg = cmpCfg.ADTree.ActionsList.Style
		p.style = &t.ADTree.ActionsList.Style

	case 24:
		p.rootCfg = &cfg.ADTree.ActionsList.Nodes
		p.cmpCfg = cmpCfg.ADTree.ActionsList.Nodes
		p.style = &t.ADTree.ActionsList.Nodes

	case 25:
		p.rootCfg = &cfg.ADTree.Status
		p.cmpCfg = cmpCfg.ADTree.Status
		p.style = &t.ADTree.Status

	case 26:
		p.rootCfg = &cfg.TabsPane.ArrowStyle
		p.cmpCfg = cmpCfg.TabsPane.ArrowStyle
		p.style = &t.TabsPane.ArrowStyle

	case 27:
		p.rootCfg = &cfg.TabsPane.Tab
		p.cmpCfg = cmpCfg.TabsPane.Tab
		p.style = &t.TabsPane.Tab

	case 28:
		p.rootCfg = &cfg.TabsPane.FocusedTab
		p.cmpCfg = cmpCfg.TabsPane.FocusedTab
		p.style = &t.TabsPane.FocusedTab

	case 29:
		p.rootCfg = &cfg.Info.Title
		p.cmpCfg = cmpCfg.Info.Title
		p.style = &t.Info.Title

	case 30:
		p.rootCfg = &cfg.Info.PropertyName
		p.cmpCfg = cmpCfg.Info.PropertyName
		p.style = &t.Info.PropertyName

	case 31:
		p.rootCfg = &cfg.Info.PropertyValue
		p.cmpCfg = cmpCfg.Info.PropertyValue
		p.style = &t.Info.PropertyValue

	case 32:
		p.rootCfg = &cfg.Operations.Title
		p.cmpCfg = cmpCfg.Operations.Title
		p.style = &t.Operations.Title

	case 33:
		p.rootCfg = &cfg.Operations.Selection
		p.cmpCfg = cmpCfg.Operations.Selection
		p.style = &t.Operations.Selection

	case 34:
		p.rootCfg = &cfg.Operations.OperationNumber
		p.cmpCfg = cmpCfg.Operations.OperationNumber
		p.style = &t.Operations.OperationNumber

	case 35:
		p.rootCfg = &cfg.Operations.Time
		p.cmpCfg = cmpCfg.Operations.Time
		p.style = &t.Operations.Time

	case 36:
		p.rootCfg = &cfg.Operations.PropertyName
		p.cmpCfg = cmpCfg.Operations.PropertyName
		p.style = &t.Operations.PropertyName

	case 37:
		p.rootCfg = &cfg.Operations.Error
		p.cmpCfg = cmpCfg.Operations.Error
		p.style = &t.Operations.Error

	case 38:
		p.rootCfg = &cfg.Operations.Completed
		p.cmpCfg = cmpCfg.Operations.Completed
		p.style = &t.Operations.Completed

	case 39:
		p.rootCfg = &cfg.Operations.InProgress
		p.cmpCfg = cmpCfg.Operations.InProgress
		p.style = &t.Operations.InProgress

	case 40:
		p.rootCfg = &cfg.Operations.Message
		p.cmpCfg = cmpCfg.Operations.Message
		p.style = &t.Operations.Message

	case 41:
		p.rootCfg = &cfg.Log.Title
		p.cmpCfg = cmpCfg.Log.Title
		p.style = &t.Log.Title

	case 42:
		p.rootCfg = &cfg.Log.Time
		p.cmpCfg = cmpCfg.Log.Time
		p.style = &t.Log.Time

	case 43:
		p.rootCfg = &cfg.Log.Info
		p.cmpCfg = cmpCfg.Log.Info
		p.style = &t.Log.Info

	case 44:
		p.rootCfg = &cfg.Log.Debug
		p.cmpCfg = cmpCfg.Log.Debug
		p.style = &t.Log.Debug

	case 45:
		p.rootCfg = &cfg.Log.Error
		p.cmpCfg = cmpCfg.Log.Error
		p.style = &t.Log.Error

	case 46:
		p.rootCfg = &cfg.StatusBar.Style
		p.cmpCfg = cmpCfg.StatusBar.Style
		p.style = &t.StatusBar.Style

	}

	return p
}
