package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"github.com/dave/dst/dstutil"
	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

type GenOptions struct {
	pkgName string

	currentFilePath, currentStructName string

	newFilePath, newStructName, newStructComment string
}

type GenTempl interface {
	AppendAccessor(s string) (string, bool)
	GetPartialCode() string
}

func generateStruct(tpl GenTempl, g *GenOptions) error {
	newFileName := filepath.Base(g.newFilePath)

	fset := token.NewFileSet()

	cfgDst, err := decorator.ParseFile(fset, g.currentFilePath, nil, parser.AllErrors)
	if err != nil {
		return err
	}

	var parentNode dst.Node
	var tspec *dst.TypeSpec
	var stype *dst.StructType

	dstutil.Apply(cfgDst, func(c *dstutil.Cursor) bool {
		n := c.Node()
		if n == nil {
			return true
		}

		switch v := n.(type) {
		case *dst.GenDecl:
			if v.Tok != token.TYPE {
				deleteNodeFromCursor(c)
				return true
			}

			for _, spec := range v.Specs {
				ts, st, exists := matchStructType(spec, g.currentStructName)
				switch {
				case !exists:
					deleteNodeFromCursor(c)
					return true

				case exists:
					tspec = ts
					stype = st
					parentNode = v

					return true
				}
			}

		case *dst.FuncDecl:
			if !matchFuncRecvType(v, g.newStructName) {
				deleteNodeFromCursor(c)
			}

		default:
		}

		return true
	}, nil)

	modifyStruct(
		newModStructArg(fset, cfgDst, tpl, g).
			setNodes(parentNode, tspec, stype),
	)

	return writeCodeToFile(cfgDst, g.pkgName, newFileName, g.newFilePath)
}

func writeCodeToFile(generatedDst *dst.File, pkgName, fileName, filePath string) error {
	impDir, closeFunc, err := prepareAllImports(pkgName)
	if err != nil {
		return err
	}
	defer closeFunc()

	var b bytes.Buffer
	defer b.Reset()

	decorator.Fprint(&b, generatedDst)

	proc, err := imports.Process(filepath.Join(impDir, fileName), b.Bytes(), nil)
	if err != nil {
		return err
	}

	file, err := openFileToWrite(filePath)
	if err != nil {
		return err
	}

	_, err = file.WriteString("// Code generated by structgen. DO NOT EDIT.\n\n")
	if err != nil {
		return err
	}

	_, err = file.Write(proc)
	if err != nil {
		return err
	}

	return file.Close()
}

func matchStructType(n dst.Node, name string) (ts *dst.TypeSpec, st *dst.StructType, exists bool) {
	typeSpec, ok := n.(*dst.TypeSpec)
	if !ok {
		return nil, nil, false
	}

	st, ok = typeSpec.Type.(*dst.StructType)
	if !ok {
		return nil, nil, false
	}

	return typeSpec, st, typeSpec.Name.Name == name
}

func matchFuncRecvType(fnType *dst.FuncDecl, recvTypeName string) (exists bool) {
	recv := fnType.Recv
	if recv == nil || len(recv.List) == 0 {
		return false
	}

	for _, rt := range recv.List {
		expr := rt.Type
		if expr == nil {
			continue
		}

		switch v := expr.(type) {
		case *dst.Ident:
			if v.Name == recvTypeName {
				return true
			}

		case *dst.StarExpr:
			if ident, ok := v.X.(*dst.Ident); ok && ident.Name == recvTypeName {
				return true
			}
		}
	}

	return false
}

type modStructArg struct {
	fset *token.FileSet

	cfgFile    *dst.File
	parentNode dst.Node

	ts *dst.TypeSpec
	st *dst.StructType

	tpl GenTempl
	*GenOptions
}

func newModStructArg(fset *token.FileSet, cfgFile *dst.File, tpl GenTempl, g *GenOptions) *modStructArg {
	return &modStructArg{fset: fset, cfgFile: cfgFile, tpl: tpl, GenOptions: g}
}

func (m *modStructArg) setNodes(parentNode dst.Node, ts *dst.TypeSpec, st *dst.StructType) *modStructArg {
	m.parentNode = parentNode
	m.ts = ts
	m.st = st

	return m
}

func modifyStruct(v *modStructArg) {
	v.ts.Name.Name = v.newStructName

	decs := v.parentNode.Decorations()
	decs.Before = dst.EmptyLine
	decs.After = dst.EmptyLine
	decs.Start.Clear()
	decs.Start.Append(v.newStructComment)

	genStructAndAccessors(v.st, v.tpl, v.GenOptions, "")

	f, err := decorator.ParseFile(v.fset, "part.go", v.tpl.GetPartialCode(), parser.AllErrors)
	if err != nil {
		exit(err)
	}

	v.cfgFile.Decls = append(v.cfgFile.Decls, f.Decls...)
}

func genStructAndAccessors(st *dst.StructType, tpl GenTempl, opt *GenOptions, prefix string) {
	for _, field := range st.Fields.List {
		for _, name := range field.Names {
			name := name.Name

			if prefix != "" {
				name = prefix + "." + name
			}

			switch ft := field.Type.(type) {
			case *dst.StructType:
				genStructAndAccessors(ft, tpl, opt, name)
				continue

			case *dst.Ident:
				typeName, ok := tpl.AppendAccessor(name)
				if !ok || typeName == "" {
					continue
				}

				field.Type = &dst.Ident{
					Name: typeName,
				}
			}
		}
	}
}

func deleteNodeFromCursor(c *dstutil.Cursor) {
	if c.Index() >= 0 {
		c.Delete()
	}
}

func prepareAllImports(pkgName string) (impDir string, closeFunc func(), err error) {
	impDir, err = os.MkdirTemp("", "bluetuith-themegen-*")
	if err != nil {
		return "", nil, err
	}

	projPath, err := projDirPath()
	if err != nil {
		return "", nil, err
	}

	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedImports | packages.NeedFiles,
		Dir:  projPath,
	}, "./...")
	if err != nil {
		return "", nil, err
	}

	var sb strings.Builder

	fmt.Fprintf(&sb, "package %s\n\nimport (\n", pkgName)

	importMap := make(map[string]string)
	for _, pkg := range pkgs {
		for _, imp := range pkg.Imports {
			importMap[imp.PkgPath] = imp.Name
		}
	}

	for importPath := range importMap {
		fmt.Fprintf(&sb, `"%s"`, importPath)
		sb.WriteString("\n")
	}

	sb.WriteString(")")

	fp := path.Join(impDir, "imports.go")
	file, err := openFileToWrite(fp)
	if err != nil {
		return "", nil, err
	}

	file.WriteString(sb.String())

	if err := file.Close(); err != nil {
		return "", nil, err
	}

	return impDir, func() {
		if err := os.Remove(fp); err != nil {
			panic(err)
		}

		if err := os.Remove(impDir); err != nil {
			panic(err)
		}
	}, nil
}

func projDirPath() (string, error) {
	cmd := exec.Command("go", "env", "GOMOD")

	out, err := cmd.Output()
	if err != nil {
		return "", err
	}

	str := string(out)
	str = strings.TrimSpace(str)

	if str == "" {
		return "", errors.New("GOMOD not found")
	}

	return filepath.Dir(filepath.Clean(str)), nil
}

func openFileToWrite(filePath string) (*os.File, error) {
	file, err := os.OpenFile(filePath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, os.ModePerm)
	return file, err
}

//revive:disable
func exit(msg any) {
	fmt.Println(msg)

	os.Exit(1)
}
