package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"

	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"github.com/dave/dst/dstutil"
	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

func buildSelectorExpr(sel string) dst.Expr {
	if len(sel) == 0 {
		return nil
	}

	p := strings.Split(sel, ".")

	var expr dst.Expr = dst.NewIdent(p[0])
	for _, part := range p[1:] {
		expr = &dst.SelectorExpr{
			X:   expr,
			Sel: dst.NewIdent(part),
		}
	}

	return expr
}

func getAccessor(s string) (k string, v string) {
	idx := strings.LastIndex(s, ".")
	if idx == -1 {
		return "", s
	}

	return s[:idx], s[idx+1:]
}

func deleteNodeFromCursor(c *dstutil.Cursor) {
	if c.Index() >= 0 {
		c.Delete()
	}
}

func prepareAllImports(pkgName string) (impDir string, closeFunc func(), err error) {
	impDir, err = os.MkdirTemp("", "bluetuith-themegen-*")
	if err != nil {
		return "", nil, err
	}

	projPath, err := projDirPath()
	if err != nil {
		return "", nil, err
	}

	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedImports | packages.NeedFiles,
		Dir:  projPath,
	}, "./...")
	if err != nil {
		return "", nil, err
	}

	var sb strings.Builder

	fmt.Fprintf(&sb, "package %s\n\nimport (\n", pkgName)

	importMap := make(map[string]string)
	for _, pkg := range pkgs {
		for _, imp := range pkg.Imports {
			importMap[imp.PkgPath] = imp.Name
		}
	}

	for importPath := range importMap {
		fmt.Fprintf(&sb, `"%s"`, importPath)
		sb.WriteString("\n")
	}

	sb.WriteString(")")

	fp := path.Join(impDir, "imports.go")
	file, err := openFileToWrite(fp)
	if err != nil {
		return "", nil, err
	}

	file.WriteString(sb.String())

	if err := file.Close(); err != nil {
		return "", nil, err
	}

	return impDir, func() {
		if err := os.Remove(fp); err != nil {
			panic(err)
		}

		if err := os.Remove(impDir); err != nil {
			panic(err)
		}
	}, nil
}

func writeCodeToFile(generatedDst *dst.File, pkgName, filePath string, writeGenComment bool) error {
	fileName := filepath.Base(filePath)
	impDir, closeFunc, err := prepareAllImports(pkgName)
	if err != nil {
		return err
	}
	defer closeFunc()

	var b bytes.Buffer
	defer b.Reset()

	decorator.Fprint(&b, generatedDst)

	proc, err := imports.Process(filepath.Join(impDir, fileName), b.Bytes(), nil)
	if err != nil {
		return err
	}

	file, err := openFileToWrite(filePath)
	if err != nil {
		return err
	}

	if writeGenComment {
		_, err = file.WriteString("// Code generated by structgen. DO NOT EDIT.\n\n")
		if err != nil {
			return err
		}
	}

	_, err = file.Write(proc)
	if err != nil {
		return err
	}

	return file.Close()
}

func projDirPath() (string, error) {
	cmd := exec.Command("go", "env", "GOMOD")

	out, err := cmd.Output()
	if err != nil {
		return "", err
	}

	str := string(out)
	str = strings.TrimSpace(str)

	if str == "" {
		return "", errors.New("GOMOD not found")
	}

	return filepath.Dir(filepath.Clean(str)), nil
}

func openFileToWrite(filePath string) (*os.File, error) {
	file, err := os.OpenFile(filePath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, os.ModePerm)
	return file, err
}

func execute(cmd string, params ...string) ([]byte, error) {
	c := exec.Command(cmd, params...)

	return c.Output()
}

//revive:disable
func exit(msg any) {
	fmt.Println(msg)

	os.Exit(1)
}
